import request from 'supertest';
import { app } from '../src/app';

beforeAll(() => {
  process.env.NODE_ENV = 'test';
});

beforeEach(() => {
  process.env.TMDB_API_KEY = 'TEST API KEY';
  global.fetch = jest.fn();
});

afterEach(() => {
  delete process.env.TMDB_API_KEY;
  jest.restoreAllMocks();
});

describe('Get featured movies', () => {
  it('GET /api/movies/featured should return featured movies', async () => {
    const mockResult = {
      page: 1,
      results: [
        {
          adult: false,
          backdrop_path: '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
          id: 687163,
          title: 'Project Hail Mary',
          original_title: 'Project Hail Mary',
          overview:
            'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction… but an unexpected friendship means he may not have to do it alone.',
          poster_path: '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [878, 12],
          popularity: 269.6938,
          release_date: '2026-03-15',
          video: false,
          vote_average: 8.215,
          vote_count: 1551,
        },
        {
          adult: false,
          backdrop_path: '/9Z2uDYXqJrlmePznQQJhL6d92Rq.jpg',
          id: 1226863,
          title: 'The Super Mario Galaxy Movie',
          original_title: 'The Super Mario Galaxy Movie',
          overview:
            "Having thwarted Bowser's previous plot to marry Princess Peach, Mario and Luigi now face a fresh threat in Bowser Jr., who is determined to liberate his father from captivity and restore the family legacy. Alongside companions new and old, the brothers travel across the stars to stop the young heir's crusade.",
          poster_path: '/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [10751, 35, 12, 14, 16],
          popularity: 780.1539,
          release_date: '2026-04-01',
          video: false,
          vote_average: 6.794,
          vote_count: 509,
        },
        {
          adult: false,
          backdrop_path: '/sS3zGYFPcfM5pArVNWl6qLyaSmU.jpg',
          id: 980431,
          title: 'Avatar: Aang, The Last Airbender',
          original_title: 'Avatar: Aang, The Last Airbender',
          overview:
            "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
          poster_path: '/gPiyTLo5GGwtJl0L8TlaJF9r0KE.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [16, 28, 12, 14],
          popularity: 269.687,
          release_date: '2026-10-09',
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
        {
          adult: false,
          backdrop_path: '/zc08qkHtWfZ2cQGQBK1S5yafJmR.jpg',
          id: 1304313,
          title: "Lee Cronin's The Mummy",
          original_title: "Lee Cronin's The Mummy",
          overview:
            'The young daughter of a journalist disappears into the desert without a trace—eight years later, the broken family is shocked when she is returned to them, as what should be a joyful reunion turns into a living nightmare.',
          poster_path: '/8L8efNkz8rUmwR7sV0g3vnC9yjn.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [27, 9648],
          popularity: 161.4338,
          release_date: '2026-04-15',
          video: false,
          vote_average: 6.767,
          vote_count: 85,
        },
        {
          adult: false,
          backdrop_path: '/avwIERZtWiWa34qShf5biDzAVaF.jpg',
          id: 1049471,
          title: 'Outcome',
          original_title: 'Outcome',
          overview:
            "Reef Hawk, Hollywood's poster child since age six, is not okay. When he learns about an extortion plot tied to a mysterious video, Reef preemptively sets out on a redemption tour to make amends, confront his demons, and avoid getting canceled.",
          poster_path: '/kSzcpfbTy2pXHGvrVU2WhQTo6oU.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [35, 18],
          popularity: 96.5143,
          release_date: '2026-04-06',
          video: false,
          vote_average: 5.309,
          vote_count: 116,
        },
        {
          adult: false,
          backdrop_path: '/jRsjWwZzI39bTm44FNhRtiICd9k.jpg',
          id: 1084577,
          title: 'Balls Up',
          original_title: 'Balls Up',
          overview:
            'Two marketing executives go "balls out" and pitch a bold full‑coverage condom sponsorship with the World Cup. After their drunken celebration in Brazil sparks a global scandal, they must outrun furious fans, criminals, and power-hungry officials to salvage their careers and make it home alive.',
          poster_path: '/xwvJ3WzdJ1OCuDoY8LAxBUlQyig.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [35, 28, 12],
          popularity: 203.8693,
          release_date: '2026-04-15',
          video: false,
          vote_average: 5.447,
          vote_count: 74,
        },
        {
          adult: false,
          backdrop_path: '/3ooXDVaz4xHKtwe4lkmF1gNopOC.jpg',
          id: 1290417,
          title: 'Thrash',
          original_title: 'Thrash',
          overview:
            'When a Category 5 hurricane decimates a coastal town, the storm surge brings devastation, chaos, and something far more frightening onto shore: hungry sharks.',
          poster_path: '/adk8weka3O5648g3de4z3y4aE7G.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [27, 53],
          popularity: 212.0369,
          release_date: '2026-04-10',
          video: false,
          vote_average: 5.99,
          vote_count: 335,
        },
        {
          adult: false,
          backdrop_path: '/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg',
          id: 83533,
          title: 'Avatar: Fire and Ash',
          original_title: 'Avatar: Fire and Ash',
          overview:
            "In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a violent and power-hungry Na'vi tribe led by the ruthless Varang. Jake's family must fight for their survival and the future of Pandora in a conflict that pushes them to their emotional and physical limits.",
          poster_path: '/aabwWZWx6z1aYP4PX2ADvbDKktd.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [878, 12, 14],
          popularity: 315.4011,
          release_date: '2025-12-17',
          video: false,
          vote_average: 7.372,
          vote_count: 2641,
        },
        {
          adult: false,
          backdrop_path: '/jSxeFrFCajefwka3TTRY4k8XVEX.jpg',
          id: 1266127,
          title: 'Ready or Not: Here I Come',
          original_title: 'Ready or Not: Here I Come',
          overview:
            'Moments after surviving an all-out attack from the Le Domas family, Grace discovers she’s reached the next level of the nightmarish game — and this time with her estranged sister Faith at her side. Grace has one chance to survive, keep her sister alive, and claim the High Seat of the Council that controls the world. Four rival families are hunting her for the throne, and whoever wins rules it all.',
          poster_path: '/jRf89HVEtBZiSnOXXWDhZOfuTwW.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [27, 35],
          popularity: 76.0164,
          release_date: '2026-03-19',
          video: false,
          vote_average: 6.981,
          vote_count: 233,
        },
        {
          adult: false,
          backdrop_path: '/xBT0oNq6rsTFv4SxG5uGRIEOrq6.jpg',
          id: 936075,
          title: 'Michael',
          original_title: 'Michael',
          overview:
            'Discover the story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music, tracing his journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
          poster_path: '/3Qud19bBUrrJAzy0Ilm8gRJlJXP.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [10402, 18],
          popularity: 50.0502,
          release_date: '2026-04-22',
          video: false,
          vote_average: 7.5,
          vote_count: 5,
        },
        {
          adult: false,
          backdrop_path: '/t9J2HXaDuJR7bvIG9XF7mttn4VY.jpg',
          id: 1159559,
          title: 'Scream 7',
          original_title: 'Scream 7',
          overview:
            'When a new Ghostface killer emerges in the quiet town where Sidney Prescott has built a new life, her darkest fears are realized as her daughter becomes the next target. Determined to protect her family, Sidney must face the horrors of her past to put an end to the bloodshed once and for all.',
          poster_path: '/jjyuk0edLiW8vOSnlfwWCCLpbh5.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [27, 9648, 80],
          popularity: 127.1298,
          release_date: '2026-02-25',
          video: false,
          vote_average: 6.031,
          vote_count: 764,
        },
        {
          adult: false,
          backdrop_path: '/1oKLEA9JOhvaBwLpqjROisvWMy7.jpg',
          id: 1325734,
          title: 'The Drama',
          original_title: 'The Drama',
          overview:
            'A happily engaged couple is put to the test when an unexpected turn sends their wedding week off the rails.',
          poster_path: '/ikcNOWB6Qo1ER1H1BJL6Vf0W22s.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [10749, 35, 18],
          popularity: 48.929,
          release_date: '2026-03-26',
          video: false,
          vote_average: 7.031,
          vote_count: 454,
        },
        {
          adult: false,
          backdrop_path: '/v0NEB75SZjxY8GS3ho8WeEvjIT3.jpg',
          id: 680493,
          title: 'Return to Silent Hill',
          original_title: 'Return to Silent Hill',
          overview:
            'When James receives a mysterious letter from his lost love Mary, he is drawn to Silent Hill—a once-familiar town now consumed by darkness. As he searches for her, James faces monstrous creatures and unravels a terrifying truth that will push him to the edge of his sanity.',
          poster_path: '/fqAGFN2K2kDL0EHxvJaXzaMUkkt.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [9648, 18, 27],
          popularity: 86.3818,
          release_date: '2026-01-21',
          video: false,
          vote_average: 5.093,
          vote_count: 372,
        },
        {
          adult: false,
          backdrop_path: '/5rxEnsgriw8z065q51lrvPKYmCL.jpg',
          id: 1367642,
          title: 'Reminders of Him',
          original_title: 'Reminders of Him',
          overview:
            "When Diem's custodial grandparents adamantly refuse Kenna's attempts to see her daughter, Kenna discovers unexpected compassion, and then something truer and deeper, with former NFL player and local bar owner Ledger. As their secret romance develops, so do the dangers for both of them, leading Kenna toward heartbreak and, ultimately, the hope for a second chance.",
          poster_path: '/7L6rceYgzQ0NeHD7PRDNrRoQ291.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [10749, 18],
          popularity: 64.1082,
          release_date: '2026-03-11',
          video: false,
          vote_average: 7.1,
          vote_count: 128,
        },
        {
          adult: false,
          backdrop_path: '/hHDNOlATHhre4eZ7aYz5cdyJLik.jpg',
          id: 1272837,
          title: '28 Years Later: The Bone Temple',
          original_title: '28 Years Later: The Bone Temple',
          overview:
            "Dr. Kelson finds himself in a shocking new relationship - with consequences that could change the world as they know it - and Spike's encounter with Jimmy Crystal becomes a nightmare he can't escape.",
          poster_path: '/kK1BGkG3KAvWB0WMV1DfOx9yTMZ.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [27, 53, 878],
          popularity: 53.8672,
          release_date: '2026-01-14',
          video: false,
          vote_average: 7.151,
          vote_count: 1030,
        },
        {
          adult: false,
          backdrop_path: '/jJmlCFi5EjpH5vHmOczRiVDm0qS.jpg',
          id: 1613798,
          title: 'Vengeance',
          original_title: 'Venganza',
          overview:
            'The brutal murder of the wife of “Toro,” a military hero in the special forces, turns him into a man with a single purpose: revenge. After a stroke of fate makes him a millionaire, Carlos transforms his fortune into an arsenal and, together with his closest soldiers, sets out to hunt down those responsible.',
          poster_path: '/ygWXPL0RS91JyJPNOfK34eV3bRE.jpg',
          media_type: 'movie',
          original_language: 'es',
          genre_ids: [28, 53],
          popularity: 76.1661,
          release_date: '2026-02-26',
          video: false,
          vote_average: 6.263,
          vote_count: 19,
        },
        {
          adult: false,
          backdrop_path: '/gCmfeKmEAZBP5gcXpiqb0gii9rS.jpg',
          id: 1198994,
          title: 'Send Help',
          original_title: 'Send Help',
          overview:
            "Two colleagues become stranded on a deserted island, the only survivors of a plane crash. On the island, they must overcome past grievances and work together to survive, but ultimately, it's a battle of wills and wits to make it out alive.",
          poster_path: '/mjkS2iAgWj3ik1DTjvI15nHZ7yl.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [27, 53, 35],
          popularity: 191.8247,
          release_date: '2026-01-22',
          video: false,
          vote_average: 7.031,
          vote_count: 1023,
        },
        {
          adult: false,
          backdrop_path: '/nHxWyy18SvAZ8jJeemtS8k1UNjM.jpg',
          id: 1290821,
          title: 'Shelter',
          original_title: 'Shelter',
          overview:
            'A man living in self-imposed exile on a remote island rescues a young girl from a violent storm, setting off a chain of events that forces him out of seclusion to protect her from enemies tied to his past.',
          poster_path: '/buPFnHZ3xQy6vZEHxbHgL1Pc6CR.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [28, 80, 53],
          popularity: 202.7974,
          release_date: '2026-01-28',
          video: false,
          vote_average: 6.791,
          vote_count: 561,
        },
        {
          adult: false,
          backdrop_path: '/qXxFWyur7jFkg2aQgENcXuyYeHF.jpg',
          id: 1480387,
          title: 'undertone',
          original_title: 'undertone',
          overview:
            'The host of a popular paranormal podcast becomes haunted by terrifying recordings mysteriously sent her way.',
          poster_path: '/2PFgFMnrdCPXWiZl1PUvky7Mo9D.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [27, 9648],
          popularity: 119.4522,
          release_date: '2026-03-12',
          video: false,
          vote_average: 6.62,
          vote_count: 72,
        },
        {
          adult: false,
          backdrop_path: '/vG42HeYtoTFflqwP42wYD7tBuNr.jpg',
          id: 1171145,
          title: 'Crime 101',
          original_title: 'Crime 101',
          overview:
            'When an elusive thief whose high-stakes heists unfold along the iconic 101 freeway in Los Angeles eyes the score of a lifetime, with hopes of this being his final job, his path collides with a disillusioned insurance broker who is facing her own crossroads. Determined to crack the case, a relentless detective closes in on the operation, raising the stakes even higher.',
          poster_path: '/tVvpFIoteRHNnoZMhdnwIVwJpCA.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [80, 53],
          popularity: 167.3887,
          release_date: '2026-02-11',
          video: false,
          vote_average: 6.99,
          vote_count: 721,
        },
      ],
      total_pages: 500,
      total_results: 10000,
    };

    (global.fetch as jest.Mock).mockResolvedValue({
      ok: true,
      status: 200,
      json: async () => mockResult,
    });
    const res = await request(app).get('/api/movies/featured');

    expect(res.status).toBe(200);
    expect(res.body).toEqual([
      {
        id: 687163,
        title: 'Project Hail Mary',
        overview:
          'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction… but an unexpected friendship means he may not have to do it alone.',
        release_date: '2026-03-15',
        genre_ids: [878, 12],
        original_language: 'en',
        backdrop_path: '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
        poster_path: '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
      },
      {
        id: 1226863,
        title: 'The Super Mario Galaxy Movie',
        overview:
          "Having thwarted Bowser's previous plot to marry Princess Peach, Mario and Luigi now face a fresh threat in Bowser Jr., who is determined to liberate his father from captivity and restore the family legacy. Alongside companions new and old, the brothers travel across the stars to stop the young heir's crusade.",
        release_date: '2026-04-01',
        genre_ids: [10751, 35, 12, 14, 16],
        original_language: 'en',
        backdrop_path: '/9Z2uDYXqJrlmePznQQJhL6d92Rq.jpg',
        poster_path: '/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg',
      },
      {
        id: 980431,
        title: 'Avatar: Aang, The Last Airbender',
        overview:
          "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
        release_date: '2026-10-09',
        genre_ids: [16, 28, 12, 14],
        original_language: 'en',
        backdrop_path: '/sS3zGYFPcfM5pArVNWl6qLyaSmU.jpg',
        poster_path: '/gPiyTLo5GGwtJl0L8TlaJF9r0KE.jpg',
      },
      {
        id: 1304313,
        title: "Lee Cronin's The Mummy",
        overview:
          'The young daughter of a journalist disappears into the desert without a trace—eight years later, the broken family is shocked when she is returned to them, as what should be a joyful reunion turns into a living nightmare.',
        release_date: '2026-04-15',
        genre_ids: [27, 9648],
        original_language: 'en',
        backdrop_path: '/zc08qkHtWfZ2cQGQBK1S5yafJmR.jpg',
        poster_path: '/8L8efNkz8rUmwR7sV0g3vnC9yjn.jpg',
      },
      {
        id: 1049471,
        title: 'Outcome',
        overview:
          "Reef Hawk, Hollywood's poster child since age six, is not okay. When he learns about an extortion plot tied to a mysterious video, Reef preemptively sets out on a redemption tour to make amends, confront his demons, and avoid getting canceled.",
        release_date: '2026-04-06',
        genre_ids: [35, 18],
        original_language: 'en',
        backdrop_path: '/avwIERZtWiWa34qShf5biDzAVaF.jpg',
        poster_path: '/kSzcpfbTy2pXHGvrVU2WhQTo6oU.jpg',
      },
      {
        id: 1084577,
        title: 'Balls Up',
        overview:
          'Two marketing executives go "balls out" and pitch a bold full‑coverage condom sponsorship with the World Cup. After their drunken celebration in Brazil sparks a global scandal, they must outrun furious fans, criminals, and power-hungry officials to salvage their careers and make it home alive.',
        release_date: '2026-04-15',
        genre_ids: [35, 28, 12],
        original_language: 'en',
        backdrop_path: '/jRsjWwZzI39bTm44FNhRtiICd9k.jpg',
        poster_path: '/xwvJ3WzdJ1OCuDoY8LAxBUlQyig.jpg',
      },
      {
        id: 1290417,
        title: 'Thrash',
        overview:
          'When a Category 5 hurricane decimates a coastal town, the storm surge brings devastation, chaos, and something far more frightening onto shore: hungry sharks.',
        release_date: '2026-04-10',
        genre_ids: [27, 53],
        original_language: 'en',
        backdrop_path: '/3ooXDVaz4xHKtwe4lkmF1gNopOC.jpg',
        poster_path: '/adk8weka3O5648g3de4z3y4aE7G.jpg',
      },
      {
        id: 83533,
        title: 'Avatar: Fire and Ash',
        overview:
          "In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a violent and power-hungry Na'vi tribe led by the ruthless Varang. Jake's family must fight for their survival and the future of Pandora in a conflict that pushes them to their emotional and physical limits.",
        release_date: '2025-12-17',
        genre_ids: [878, 12, 14],
        original_language: 'en',
        backdrop_path: '/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg',
        poster_path: '/aabwWZWx6z1aYP4PX2ADvbDKktd.jpg',
      },
      {
        id: 1266127,
        title: 'Ready or Not: Here I Come',
        overview:
          'Moments after surviving an all-out attack from the Le Domas family, Grace discovers she’s reached the next level of the nightmarish game — and this time with her estranged sister Faith at her side. Grace has one chance to survive, keep her sister alive, and claim the High Seat of the Council that controls the world. Four rival families are hunting her for the throne, and whoever wins rules it all.',
        release_date: '2026-03-19',
        genre_ids: [27, 35],
        original_language: 'en',
        backdrop_path: '/jSxeFrFCajefwka3TTRY4k8XVEX.jpg',
        poster_path: '/jRf89HVEtBZiSnOXXWDhZOfuTwW.jpg',
      },
      {
        id: 936075,
        title: 'Michael',
        overview:
          'Discover the story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music, tracing his journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
        release_date: '2026-04-22',
        genre_ids: [10402, 18],
        original_language: 'en',
        backdrop_path: '/xBT0oNq6rsTFv4SxG5uGRIEOrq6.jpg',
        poster_path: '/3Qud19bBUrrJAzy0Ilm8gRJlJXP.jpg',
      },
      {
        id: 1159559,
        title: 'Scream 7',
        overview:
          'When a new Ghostface killer emerges in the quiet town where Sidney Prescott has built a new life, her darkest fears are realized as her daughter becomes the next target. Determined to protect her family, Sidney must face the horrors of her past to put an end to the bloodshed once and for all.',
        release_date: '2026-02-25',
        genre_ids: [27, 9648, 80],
        original_language: 'en',
        backdrop_path: '/t9J2HXaDuJR7bvIG9XF7mttn4VY.jpg',
        poster_path: '/jjyuk0edLiW8vOSnlfwWCCLpbh5.jpg',
      },
      {
        id: 1325734,
        title: 'The Drama',
        overview:
          'A happily engaged couple is put to the test when an unexpected turn sends their wedding week off the rails.',
        release_date: '2026-03-26',
        genre_ids: [10749, 35, 18],
        original_language: 'en',
        backdrop_path: '/1oKLEA9JOhvaBwLpqjROisvWMy7.jpg',
        poster_path: '/ikcNOWB6Qo1ER1H1BJL6Vf0W22s.jpg',
      },
      {
        id: 680493,
        title: 'Return to Silent Hill',
        overview:
          'When James receives a mysterious letter from his lost love Mary, he is drawn to Silent Hill—a once-familiar town now consumed by darkness. As he searches for her, James faces monstrous creatures and unravels a terrifying truth that will push him to the edge of his sanity.',
        release_date: '2026-01-21',
        genre_ids: [9648, 18, 27],
        original_language: 'en',
        backdrop_path: '/v0NEB75SZjxY8GS3ho8WeEvjIT3.jpg',
        poster_path: '/fqAGFN2K2kDL0EHxvJaXzaMUkkt.jpg',
      },
      {
        id: 1367642,
        title: 'Reminders of Him',
        overview:
          "When Diem's custodial grandparents adamantly refuse Kenna's attempts to see her daughter, Kenna discovers unexpected compassion, and then something truer and deeper, with former NFL player and local bar owner Ledger. As their secret romance develops, so do the dangers for both of them, leading Kenna toward heartbreak and, ultimately, the hope for a second chance.",
        release_date: '2026-03-11',
        genre_ids: [10749, 18],
        original_language: 'en',
        backdrop_path: '/5rxEnsgriw8z065q51lrvPKYmCL.jpg',
        poster_path: '/7L6rceYgzQ0NeHD7PRDNrRoQ291.jpg',
      },
      {
        id: 1272837,
        title: '28 Years Later: The Bone Temple',
        overview:
          "Dr. Kelson finds himself in a shocking new relationship - with consequences that could change the world as they know it - and Spike's encounter with Jimmy Crystal becomes a nightmare he can't escape.",
        release_date: '2026-01-14',
        genre_ids: [27, 53, 878],
        original_language: 'en',
        backdrop_path: '/hHDNOlATHhre4eZ7aYz5cdyJLik.jpg',
        poster_path: '/kK1BGkG3KAvWB0WMV1DfOx9yTMZ.jpg',
      },
      {
        id: 1613798,
        title: 'Vengeance',
        overview:
          'The brutal murder of the wife of “Toro,” a military hero in the special forces, turns him into a man with a single purpose: revenge. After a stroke of fate makes him a millionaire, Carlos transforms his fortune into an arsenal and, together with his closest soldiers, sets out to hunt down those responsible.',
        release_date: '2026-02-26',
        genre_ids: [28, 53],
        original_language: 'es',
        backdrop_path: '/jJmlCFi5EjpH5vHmOczRiVDm0qS.jpg',
        poster_path: '/ygWXPL0RS91JyJPNOfK34eV3bRE.jpg',
      },
      {
        id: 1198994,
        title: 'Send Help',
        overview:
          "Two colleagues become stranded on a deserted island, the only survivors of a plane crash. On the island, they must overcome past grievances and work together to survive, but ultimately, it's a battle of wills and wits to make it out alive.",
        release_date: '2026-01-22',
        genre_ids: [27, 53, 35],
        original_language: 'en',
        backdrop_path: '/gCmfeKmEAZBP5gcXpiqb0gii9rS.jpg',
        poster_path: '/mjkS2iAgWj3ik1DTjvI15nHZ7yl.jpg',
      },
      {
        id: 1290821,
        title: 'Shelter',
        overview:
          'A man living in self-imposed exile on a remote island rescues a young girl from a violent storm, setting off a chain of events that forces him out of seclusion to protect her from enemies tied to his past.',
        release_date: '2026-01-28',
        genre_ids: [28, 80, 53],
        original_language: 'en',
        backdrop_path: '/nHxWyy18SvAZ8jJeemtS8k1UNjM.jpg',
        poster_path: '/buPFnHZ3xQy6vZEHxbHgL1Pc6CR.jpg',
      },
      {
        id: 1480387,
        title: 'undertone',
        overview:
          'The host of a popular paranormal podcast becomes haunted by terrifying recordings mysteriously sent her way.',
        release_date: '2026-03-12',
        genre_ids: [27, 9648],
        original_language: 'en',
        backdrop_path: '/qXxFWyur7jFkg2aQgENcXuyYeHF.jpg',
        poster_path: '/2PFgFMnrdCPXWiZl1PUvky7Mo9D.jpg',
      },
      {
        id: 1171145,
        title: 'Crime 101',
        overview:
          'When an elusive thief whose high-stakes heists unfold along the iconic 101 freeway in Los Angeles eyes the score of a lifetime, with hopes of this being his final job, his path collides with a disillusioned insurance broker who is facing her own crossroads. Determined to crack the case, a relentless detective closes in on the operation, raising the stakes even higher.',
        release_date: '2026-02-11',
        genre_ids: [80, 53],
        original_language: 'en',
        backdrop_path: '/vG42HeYtoTFflqwP42wYD7tBuNr.jpg',
        poster_path: '/tVvpFIoteRHNnoZMhdnwIVwJpCA.jpg',
      },
    ]);
  });
});

describe('Get featured with custom timeframe', () => {
  it('Returns a different set of data for 1 day', async () => {
    const mockRes = {
      page: 1,
      results: [
        {
          adult: false,
          backdrop_path: '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
          id: 687163,
          title: 'Project Hail Mary',
          original_title: 'Project Hail Mary',
          overview:
            'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction… but an unexpected friendship means he may not have to do it alone.',
          poster_path: '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [878, 12],
          popularity: 269.6938,
          release_date: '2026-03-15',
          video: false,
          vote_average: 8.216,
          vote_count: 1552,
        },
        {
          adult: false,
          backdrop_path: '/9Z2uDYXqJrlmePznQQJhL6d92Rq.jpg',
          id: 1226863,
          title: 'The Super Mario Galaxy Movie',
          original_title: 'The Super Mario Galaxy Movie',
          overview:
            "Having thwarted Bowser's previous plot to marry Princess Peach, Mario and Luigi now face a fresh threat in Bowser Jr., who is determined to liberate his father from captivity and restore the family legacy. Alongside companions new and old, the brothers travel across the stars to stop the young heir's crusade.",
          poster_path: '/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [10751, 35, 12, 14, 16],
          popularity: 780.1539,
          release_date: '2026-04-01',
          video: false,
          vote_average: 6.79,
          vote_count: 510,
        },
        {
          adult: false,
          backdrop_path: '/zc08qkHtWfZ2cQGQBK1S5yafJmR.jpg',
          id: 1304313,
          title: "Lee Cronin's The Mummy",
          original_title: "Lee Cronin's The Mummy",
          overview:
            'The young daughter of a journalist disappears into the desert without a trace—eight years later, the broken family is shocked when she is returned to them, as what should be a joyful reunion turns into a living nightmare.',
          poster_path: '/8L8efNkz8rUmwR7sV0g3vnC9yjn.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [27, 9648],
          popularity: 161.4338,
          release_date: '2026-04-15',
          video: false,
          vote_average: 6.767,
          vote_count: 85,
        },
        {
          adult: false,
          backdrop_path: '/sS3zGYFPcfM5pArVNWl6qLyaSmU.jpg',
          id: 980431,
          title: 'Avatar: Aang, The Last Airbender',
          original_title: 'Avatar: Aang, The Last Airbender',
          overview:
            "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
          poster_path: '/gPiyTLo5GGwtJl0L8TlaJF9r0KE.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [16, 28, 12, 14],
          popularity: 269.687,
          release_date: '2026-10-09',
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
        {
          adult: false,
          backdrop_path: '/jJmlCFi5EjpH5vHmOczRiVDm0qS.jpg',
          id: 1613798,
          title: 'Vengeance',
          original_title: 'Venganza',
          overview:
            'The brutal murder of the wife of “Toro,” a military hero in the special forces, turns him into a man with a single purpose: revenge. After a stroke of fate makes him a millionaire, Carlos transforms his fortune into an arsenal and, together with his closest soldiers, sets out to hunt down those responsible.',
          poster_path: '/ygWXPL0RS91JyJPNOfK34eV3bRE.jpg',
          media_type: 'movie',
          original_language: 'es',
          genre_ids: [28, 53],
          popularity: 76.1661,
          release_date: '2026-02-26',
          video: false,
          vote_average: 6.263,
          vote_count: 19,
        },
        {
          adult: false,
          backdrop_path: '/6Lm7CtE0AM7FLsHagrvZJCxtgzm.jpg',
          id: 1674749,
          title: 'WWE WrestleMania 42 - Saturday',
          original_title: 'WWE WrestleMania 42 - Saturday',
          overview:
            "Cody Rhodes clashes with longtime friend Randy Orton for the Undisputed WWE Title. Women's World Champion Stephanie Vaquer to defend against Liv Morgan WrestleMania 42. Women’s Intercontinental Champion AJ Lee vs. Becky Lynch. Jacob Fatu vs. Drew McIntyre in an Unsanctioned Match. Four teams are going to battle it out for the WWE Women’s Tag Team Title. Logan Paul, Austin Theory & IShowSpeed vs. The Usos & LA Knight in a Six-Man Tag Team Match. Seth Rollins vs. Gunther.",
          poster_path: '/3ZqaqAmOusw3f2bN164niCFWqgx.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [28, 18, 35],
          popularity: 0.9975,
          release_date: '2026-04-18',
          video: false,
          vote_average: 5.3,
          vote_count: 7,
        },
        {
          adult: false,
          backdrop_path: '/cW8iKmWA6JAHgvNMyvrjqWd1dNp.jpg',
          id: 1511057,
          title: 'Roommates',
          original_title: 'Roommates',
          overview:
            'When shy college freshman Devon asks cool-girl Celeste to be her roommate, a blossoming friendship quickly spirals into a war of passive aggression.',
          poster_path: '/eW1s6omXIfVkTlmKVe9y9Dwwt4u.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [35],
          popularity: 66.8245,
          release_date: '2026-04-13',
          video: false,
          vote_average: 6.466,
          vote_count: 29,
        },
        {
          adult: false,
          backdrop_path: '/iQSXJs6RbTumcwxMjCedDoK99rx.jpg',
          id: 1659087,
          title: '180',
          original_title: '180',
          overview:
            'When an unexpected road rage incident puts his son in critical condition, an enraged father spirals down a dark path of emotional turmoil and vengeance.',
          poster_path: '/9ISjrhA38HpSSGtfiCk8lpziC3K.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [53, 80, 18],
          popularity: 59.8316,
          release_date: '2026-04-16',
          video: false,
          vote_average: 5.321,
          vote_count: 14,
        },
        {
          adult: false,
          backdrop_path: '/jRsjWwZzI39bTm44FNhRtiICd9k.jpg',
          id: 1084577,
          title: 'Balls Up',
          original_title: 'Balls Up',
          overview:
            'Two marketing executives go "balls out" and pitch a bold full‑coverage condom sponsorship with the World Cup. After their drunken celebration in Brazil sparks a global scandal, they must outrun furious fans, criminals, and power-hungry officials to salvage their careers and make it home alive.',
          poster_path: '/xwvJ3WzdJ1OCuDoY8LAxBUlQyig.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [35, 28, 12],
          popularity: 203.8693,
          release_date: '2026-04-15',
          video: false,
          vote_average: 5.447,
          vote_count: 74,
        },
        {
          adult: false,
          backdrop_path: '/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg',
          id: 83533,
          title: 'Avatar: Fire and Ash',
          original_title: 'Avatar: Fire and Ash',
          overview:
            "In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a violent and power-hungry Na'vi tribe led by the ruthless Varang. Jake's family must fight for their survival and the future of Pandora in a conflict that pushes them to their emotional and physical limits.",
          poster_path: '/aabwWZWx6z1aYP4PX2ADvbDKktd.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [878, 12, 14],
          popularity: 315.4011,
          release_date: '2025-12-17',
          video: false,
          vote_average: 7.372,
          vote_count: 2641,
        },
        {
          adult: false,
          backdrop_path: '/gCmfeKmEAZBP5gcXpiqb0gii9rS.jpg',
          id: 1198994,
          title: 'Send Help',
          original_title: 'Send Help',
          overview:
            "Two colleagues become stranded on a deserted island, the only survivors of a plane crash. On the island, they must overcome past grievances and work together to survive, but ultimately, it's a battle of wills and wits to make it out alive.",
          poster_path: '/mjkS2iAgWj3ik1DTjvI15nHZ7yl.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [27, 53, 35],
          popularity: 191.8247,
          release_date: '2026-01-22',
          video: false,
          vote_average: 7.031,
          vote_count: 1023,
        },
        {
          adult: false,
          backdrop_path: '/xBT0oNq6rsTFv4SxG5uGRIEOrq6.jpg',
          id: 936075,
          title: 'Michael',
          original_title: 'Michael',
          overview:
            'Discover the story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music, tracing his journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
          poster_path: '/3Qud19bBUrrJAzy0Ilm8gRJlJXP.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [10402, 18],
          popularity: 50.0502,
          release_date: '2026-04-22',
          video: false,
          vote_average: 7.5,
          vote_count: 5,
        },
        {
          adult: false,
          backdrop_path: '/jSxeFrFCajefwka3TTRY4k8XVEX.jpg',
          id: 1266127,
          title: 'Ready or Not: Here I Come',
          original_title: 'Ready or Not: Here I Come',
          overview:
            'Moments after surviving an all-out attack from the Le Domas family, Grace discovers she’s reached the next level of the nightmarish game — and this time with her estranged sister Faith at her side. Grace has one chance to survive, keep her sister alive, and claim the High Seat of the Council that controls the world. Four rival families are hunting her for the throne, and whoever wins rules it all.',
          poster_path: '/jRf89HVEtBZiSnOXXWDhZOfuTwW.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [27, 35],
          popularity: 76.0164,
          release_date: '2026-03-19',
          video: false,
          vote_average: 6.981,
          vote_count: 233,
        },
        {
          adult: false,
          backdrop_path: '/3ooXDVaz4xHKtwe4lkmF1gNopOC.jpg',
          id: 1290417,
          title: 'Thrash',
          original_title: 'Thrash',
          overview:
            'When a Category 5 hurricane decimates a coastal town, the storm surge brings devastation, chaos, and something far more frightening onto shore: hungry sharks.',
          poster_path: '/adk8weka3O5648g3de4z3y4aE7G.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [27, 53],
          popularity: 212.0369,
          release_date: '2026-04-10',
          video: false,
          vote_average: 5.99,
          vote_count: 335,
        },
        {
          adult: false,
          backdrop_path: '/avwIERZtWiWa34qShf5biDzAVaF.jpg',
          id: 1049471,
          title: 'Outcome',
          original_title: 'Outcome',
          overview:
            "Reef Hawk, Hollywood's poster child since age six, is not okay. When he learns about an extortion plot tied to a mysterious video, Reef preemptively sets out on a redemption tour to make amends, confront his demons, and avoid getting canceled.",
          poster_path: '/kSzcpfbTy2pXHGvrVU2WhQTo6oU.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [35, 18],
          popularity: 96.5143,
          release_date: '2026-04-06',
          video: false,
          vote_average: 5.309,
          vote_count: 116,
        },
        {
          adult: false,
          backdrop_path: '/vG42HeYtoTFflqwP42wYD7tBuNr.jpg',
          id: 1171145,
          title: 'Crime 101',
          original_title: 'Crime 101',
          overview:
            'When an elusive thief whose high-stakes heists unfold along the iconic 101 freeway in Los Angeles eyes the score of a lifetime, with hopes of this being his final job, his path collides with a disillusioned insurance broker who is facing her own crossroads. Determined to crack the case, a relentless detective closes in on the operation, raising the stakes even higher.',
          poster_path: '/tVvpFIoteRHNnoZMhdnwIVwJpCA.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [80, 53],
          popularity: 167.3887,
          release_date: '2026-02-11',
          video: false,
          vote_average: 6.99,
          vote_count: 721,
        },
        {
          adult: false,
          backdrop_path: '/A2tzVTVtnTvpji96IZmleN78KKv.jpg',
          id: 1239134,
          title: 'Bhooth Bangla',
          original_title: 'Bhooth Bangla',
          overview:
            "A man inherits a palace in rural Mangalpur and plans his sister's wedding there, but strange supernatural events and panicked locals force him to investigate the property's mysterious past.",
          poster_path: '/ArIS4vwUxdhm3j7tsTHmffdfU8W.jpg',
          media_type: 'movie',
          original_language: 'hi',
          genre_ids: [27, 35],
          popularity: 12.0175,
          release_date: '2026-04-16',
          video: false,
          vote_average: 6.667,
          vote_count: 4,
        },
        {
          adult: false,
          backdrop_path: '/u53UYu5XG2hNgWGvs3xGhAVzypl.jpg',
          id: 1327819,
          title: 'Hoppers',
          original_title: 'Hoppers',
          overview:
            "Scientists have discovered how to 'hop' human consciousness into lifelike robotic animals, allowing people to communicate with animals as animals. Animal lover Mabel seizes an opportunity to use the technology, uncovering mysteries within the animal world beyond anything she could have imagined.",
          poster_path: '/xjtWQ2CL1mpmMNwuU5HeS4Iuwuu.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [16, 10751, 878, 35, 12],
          popularity: 219.481,
          release_date: '2026-03-04',
          video: false,
          vote_average: 7.581,
          vote_count: 480,
        },
        {
          adult: false,
          backdrop_path: '/5rxEnsgriw8z065q51lrvPKYmCL.jpg',
          id: 1367642,
          title: 'Reminders of Him',
          original_title: 'Reminders of Him',
          overview:
            "When Diem's custodial grandparents adamantly refuse Kenna's attempts to see her daughter, Kenna discovers unexpected compassion, and then something truer and deeper, with former NFL player and local bar owner Ledger. As their secret romance develops, so do the dangers for both of them, leading Kenna toward heartbreak and, ultimately, the hope for a second chance.",
          poster_path: '/7L6rceYgzQ0NeHD7PRDNrRoQ291.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [10749, 18],
          popularity: 64.1082,
          release_date: '2026-03-11',
          video: false,
          vote_average: 7.1,
          vote_count: 128,
        },
        {
          adult: false,
          backdrop_path: '/1oKLEA9JOhvaBwLpqjROisvWMy7.jpg',
          id: 1325734,
          title: 'The Drama',
          original_title: 'The Drama',
          overview:
            'A happily engaged couple is put to the test when an unexpected turn sends their wedding week off the rails.',
          poster_path: '/ikcNOWB6Qo1ER1H1BJL6Vf0W22s.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [10749, 35, 18],
          popularity: 48.929,
          release_date: '2026-03-26',
          video: false,
          vote_average: 7.033,
          vote_count: 456,
        },
      ],
      total_pages: 500,
      total_results: 10000,
    };
    (global.fetch as jest.Mock).mockResolvedValue({
      ok: true,
      status: 200,
      json: async () => mockRes,
    });
    const res = await request(app).get('/api/movies/featured?timeframe=day');

    expect(res.status).toBe(200);
    expect(res.body).toEqual([
      {
        id: 687163,
        title: 'Project Hail Mary',
        overview:
          'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction… but an unexpected friendship means he may not have to do it alone.',
        release_date: '2026-03-15',
        genre_ids: [878, 12],
        original_language: 'en',
        backdrop_path: '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
        poster_path: '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
      },
      {
        id: 1226863,
        title: 'The Super Mario Galaxy Movie',
        overview:
          "Having thwarted Bowser's previous plot to marry Princess Peach, Mario and Luigi now face a fresh threat in Bowser Jr., who is determined to liberate his father from captivity and restore the family legacy. Alongside companions new and old, the brothers travel across the stars to stop the young heir's crusade.",
        release_date: '2026-04-01',
        genre_ids: [10751, 35, 12, 14, 16],
        original_language: 'en',
        backdrop_path: '/9Z2uDYXqJrlmePznQQJhL6d92Rq.jpg',
        poster_path: '/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg',
      },
      {
        id: 1304313,
        title: "Lee Cronin's The Mummy",
        overview:
          'The young daughter of a journalist disappears into the desert without a trace—eight years later, the broken family is shocked when she is returned to them, as what should be a joyful reunion turns into a living nightmare.',
        release_date: '2026-04-15',
        genre_ids: [27, 9648],
        original_language: 'en',
        backdrop_path: '/zc08qkHtWfZ2cQGQBK1S5yafJmR.jpg',
        poster_path: '/8L8efNkz8rUmwR7sV0g3vnC9yjn.jpg',
      },
      {
        id: 980431,
        title: 'Avatar: Aang, The Last Airbender',
        overview:
          "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
        release_date: '2026-10-09',
        genre_ids: [16, 28, 12, 14],
        original_language: 'en',
        backdrop_path: '/sS3zGYFPcfM5pArVNWl6qLyaSmU.jpg',
        poster_path: '/gPiyTLo5GGwtJl0L8TlaJF9r0KE.jpg',
      },
      {
        id: 1613798,
        title: 'Vengeance',
        overview:
          'The brutal murder of the wife of “Toro,” a military hero in the special forces, turns him into a man with a single purpose: revenge. After a stroke of fate makes him a millionaire, Carlos transforms his fortune into an arsenal and, together with his closest soldiers, sets out to hunt down those responsible.',
        release_date: '2026-02-26',
        genre_ids: [28, 53],
        original_language: 'es',
        backdrop_path: '/jJmlCFi5EjpH5vHmOczRiVDm0qS.jpg',
        poster_path: '/ygWXPL0RS91JyJPNOfK34eV3bRE.jpg',
      },
      {
        id: 1674749,
        title: 'WWE WrestleMania 42 - Saturday',
        overview:
          "Cody Rhodes clashes with longtime friend Randy Orton for the Undisputed WWE Title. Women's World Champion Stephanie Vaquer to defend against Liv Morgan WrestleMania 42. Women’s Intercontinental Champion AJ Lee vs. Becky Lynch. Jacob Fatu vs. Drew McIntyre in an Unsanctioned Match. Four teams are going to battle it out for the WWE Women’s Tag Team Title. Logan Paul, Austin Theory & IShowSpeed vs. The Usos & LA Knight in a Six-Man Tag Team Match. Seth Rollins vs. Gunther.",
        release_date: '2026-04-18',
        genre_ids: [28, 18, 35],
        original_language: 'en',
        backdrop_path: '/6Lm7CtE0AM7FLsHagrvZJCxtgzm.jpg',
        poster_path: '/3ZqaqAmOusw3f2bN164niCFWqgx.jpg',
      },
      {
        id: 1511057,
        title: 'Roommates',
        overview:
          'When shy college freshman Devon asks cool-girl Celeste to be her roommate, a blossoming friendship quickly spirals into a war of passive aggression.',
        release_date: '2026-04-13',
        genre_ids: [35],
        original_language: 'en',
        backdrop_path: '/cW8iKmWA6JAHgvNMyvrjqWd1dNp.jpg',
        poster_path: '/eW1s6omXIfVkTlmKVe9y9Dwwt4u.jpg',
      },
      {
        id: 1659087,
        title: '180',
        overview:
          'When an unexpected road rage incident puts his son in critical condition, an enraged father spirals down a dark path of emotional turmoil and vengeance.',
        release_date: '2026-04-16',
        genre_ids: [53, 80, 18],
        original_language: 'en',
        backdrop_path: '/iQSXJs6RbTumcwxMjCedDoK99rx.jpg',
        poster_path: '/9ISjrhA38HpSSGtfiCk8lpziC3K.jpg',
      },
      {
        id: 1084577,
        title: 'Balls Up',
        overview:
          'Two marketing executives go "balls out" and pitch a bold full‑coverage condom sponsorship with the World Cup. After their drunken celebration in Brazil sparks a global scandal, they must outrun furious fans, criminals, and power-hungry officials to salvage their careers and make it home alive.',
        release_date: '2026-04-15',
        genre_ids: [35, 28, 12],
        original_language: 'en',
        backdrop_path: '/jRsjWwZzI39bTm44FNhRtiICd9k.jpg',
        poster_path: '/xwvJ3WzdJ1OCuDoY8LAxBUlQyig.jpg',
      },
      {
        id: 83533,
        title: 'Avatar: Fire and Ash',
        overview:
          "In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a violent and power-hungry Na'vi tribe led by the ruthless Varang. Jake's family must fight for their survival and the future of Pandora in a conflict that pushes them to their emotional and physical limits.",
        release_date: '2025-12-17',
        genre_ids: [878, 12, 14],
        original_language: 'en',
        backdrop_path: '/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg',
        poster_path: '/aabwWZWx6z1aYP4PX2ADvbDKktd.jpg',
      },
      {
        id: 1198994,
        title: 'Send Help',
        overview:
          "Two colleagues become stranded on a deserted island, the only survivors of a plane crash. On the island, they must overcome past grievances and work together to survive, but ultimately, it's a battle of wills and wits to make it out alive.",
        release_date: '2026-01-22',
        genre_ids: [27, 53, 35],
        original_language: 'en',
        backdrop_path: '/gCmfeKmEAZBP5gcXpiqb0gii9rS.jpg',
        poster_path: '/mjkS2iAgWj3ik1DTjvI15nHZ7yl.jpg',
      },
      {
        id: 936075,
        title: 'Michael',
        overview:
          'Discover the story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music, tracing his journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
        release_date: '2026-04-22',
        genre_ids: [10402, 18],
        original_language: 'en',
        backdrop_path: '/xBT0oNq6rsTFv4SxG5uGRIEOrq6.jpg',
        poster_path: '/3Qud19bBUrrJAzy0Ilm8gRJlJXP.jpg',
      },
      {
        id: 1266127,
        title: 'Ready or Not: Here I Come',
        overview:
          'Moments after surviving an all-out attack from the Le Domas family, Grace discovers she’s reached the next level of the nightmarish game — and this time with her estranged sister Faith at her side. Grace has one chance to survive, keep her sister alive, and claim the High Seat of the Council that controls the world. Four rival families are hunting her for the throne, and whoever wins rules it all.',
        release_date: '2026-03-19',
        genre_ids: [27, 35],
        original_language: 'en',
        backdrop_path: '/jSxeFrFCajefwka3TTRY4k8XVEX.jpg',
        poster_path: '/jRf89HVEtBZiSnOXXWDhZOfuTwW.jpg',
      },
      {
        id: 1290417,
        title: 'Thrash',
        overview:
          'When a Category 5 hurricane decimates a coastal town, the storm surge brings devastation, chaos, and something far more frightening onto shore: hungry sharks.',
        release_date: '2026-04-10',
        genre_ids: [27, 53],
        original_language: 'en',
        backdrop_path: '/3ooXDVaz4xHKtwe4lkmF1gNopOC.jpg',
        poster_path: '/adk8weka3O5648g3de4z3y4aE7G.jpg',
      },
      {
        id: 1049471,
        title: 'Outcome',
        overview:
          "Reef Hawk, Hollywood's poster child since age six, is not okay. When he learns about an extortion plot tied to a mysterious video, Reef preemptively sets out on a redemption tour to make amends, confront his demons, and avoid getting canceled.",
        release_date: '2026-04-06',
        genre_ids: [35, 18],
        original_language: 'en',
        backdrop_path: '/avwIERZtWiWa34qShf5biDzAVaF.jpg',
        poster_path: '/kSzcpfbTy2pXHGvrVU2WhQTo6oU.jpg',
      },
      {
        id: 1171145,
        title: 'Crime 101',
        overview:
          'When an elusive thief whose high-stakes heists unfold along the iconic 101 freeway in Los Angeles eyes the score of a lifetime, with hopes of this being his final job, his path collides with a disillusioned insurance broker who is facing her own crossroads. Determined to crack the case, a relentless detective closes in on the operation, raising the stakes even higher.',
        release_date: '2026-02-11',
        genre_ids: [80, 53],
        original_language: 'en',
        backdrop_path: '/vG42HeYtoTFflqwP42wYD7tBuNr.jpg',
        poster_path: '/tVvpFIoteRHNnoZMhdnwIVwJpCA.jpg',
      },
      {
        id: 1239134,
        title: 'Bhooth Bangla',
        overview:
          "A man inherits a palace in rural Mangalpur and plans his sister's wedding there, but strange supernatural events and panicked locals force him to investigate the property's mysterious past.",
        release_date: '2026-04-16',
        genre_ids: [27, 35],
        original_language: 'hi',
        backdrop_path: '/A2tzVTVtnTvpji96IZmleN78KKv.jpg',
        poster_path: '/ArIS4vwUxdhm3j7tsTHmffdfU8W.jpg',
      },
      {
        id: 1327819,
        title: 'Hoppers',
        overview:
          "Scientists have discovered how to 'hop' human consciousness into lifelike robotic animals, allowing people to communicate with animals as animals. Animal lover Mabel seizes an opportunity to use the technology, uncovering mysteries within the animal world beyond anything she could have imagined.",
        release_date: '2026-03-04',
        genre_ids: [16, 10751, 878, 35, 12],
        original_language: 'en',
        backdrop_path: '/u53UYu5XG2hNgWGvs3xGhAVzypl.jpg',
        poster_path: '/xjtWQ2CL1mpmMNwuU5HeS4Iuwuu.jpg',
      },
      {
        id: 1367642,
        title: 'Reminders of Him',
        overview:
          "When Diem's custodial grandparents adamantly refuse Kenna's attempts to see her daughter, Kenna discovers unexpected compassion, and then something truer and deeper, with former NFL player and local bar owner Ledger. As their secret romance develops, so do the dangers for both of them, leading Kenna toward heartbreak and, ultimately, the hope for a second chance.",
        release_date: '2026-03-11',
        genre_ids: [10749, 18],
        original_language: 'en',
        backdrop_path: '/5rxEnsgriw8z065q51lrvPKYmCL.jpg',
        poster_path: '/7L6rceYgzQ0NeHD7PRDNrRoQ291.jpg',
      },
      {
        id: 1325734,
        title: 'The Drama',
        overview:
          'A happily engaged couple is put to the test when an unexpected turn sends their wedding week off the rails.',
        release_date: '2026-03-26',
        genre_ids: [10749, 35, 18],
        original_language: 'en',
        backdrop_path: '/1oKLEA9JOhvaBwLpqjROisvWMy7.jpg',
        poster_path: '/ikcNOWB6Qo1ER1H1BJL6Vf0W22s.jpg',
      },
    ]);
  });
});

describe('Get featured with different lang', () => {
  it('Returns the featured for 1 day in es-AR', async () => {
    const mockRes = {
      page: 1,
      results: [
        {
          adult: false,
          backdrop_path: '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
          id: 687163,
          title: 'Proyecto Salvación',
          original_title: 'Project Hail Mary',
          overview:
            'El profesor de ciencias Ryland Grace se despierta en una nave espacial a años luz de casa sin recordar quién es ni cómo ha llegado hasta allí. A medida que recupera la memoria, empieza a descubrir su misión: resolver el enigma de la misteriosa sustancia que provoca la extinción del sol. Deberá recurrir a sus conocimientos científicos y a sus ideas poco ortodoxas para salvar todo lo que hay en la Tierra de la extinción... pero una amistad inesperada significa que quizá no tenga que hacerlo solo.',
          poster_path: '/7lwOTxajURKEWO6gI370NTrVdBO.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [878, 12],
          popularity: 269.6938,
          release_date: '2026-03-15',
          video: false,
          vote_average: 8.216,
          vote_count: 1552,
        },
        {
          adult: false,
          backdrop_path: '/9Z2uDYXqJrlmePznQQJhL6d92Rq.jpg',
          id: 1226863,
          title: 'Super Mario Galaxy la película',
          original_title: 'The Super Mario Galaxy Movie',
          overview:
            "Secuela de 'Super Mario Bros: La película', basada en la saga 'Mario Galaxy'. Los hermanos Mario y Luigi y la princesa Peach emprenden una aventura hasta los confines del espacio y a través de la galaxia.",
          poster_path: '/79EVB4qhyfrdlMgT8GIRAikdzsQ.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [10751, 35, 12, 14, 16],
          popularity: 780.1539,
          release_date: '2026-04-01',
          video: false,
          vote_average: 6.79,
          vote_count: 510,
        },
        {
          adult: false,
          backdrop_path: '/sS3zGYFPcfM5pArVNWl6qLyaSmU.jpg',
          id: 980431,
          title: 'La leyenda de Aang: El último Airbender',
          original_title: 'Avatar: Aang, The Last Airbender',
          overview:
            "Película de animación que seguirá a Aang y sus amigos, ahora como jóvenes adultos, varios años después de los acontecimientos del final de 'Avatar: The Last Airbender'.",
          poster_path: '/gPiyTLo5GGwtJl0L8TlaJF9r0KE.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [16, 28, 12, 14],
          popularity: 269.687,
          release_date: '2026-10-09',
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
        {
          adult: false,
          backdrop_path: '/zc08qkHtWfZ2cQGQBK1S5yafJmR.jpg',
          id: 1304313,
          title: 'La momia de Lee Cronin',
          original_title: "Lee Cronin's The Mummy",
          overview:
            'La joven hija de un periodista desaparece en el desierto sin dejar rastro—ocho años más tarde, la familia rota se conmociona cuando ella es devuelta a ellos, y lo que debiera haber sido una reunión jubilosa se convierte en una auténtica pesadilla.',
          poster_path: '/hGgSpTX2f3ShFD41Ul0vcY3DSHb.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [27, 9648],
          popularity: 161.4338,
          release_date: '2026-04-15',
          video: false,
          vote_average: 6.767,
          vote_count: 85,
        },
        {
          adult: false,
          backdrop_path: '/cW8iKmWA6JAHgvNMyvrjqWd1dNp.jpg',
          id: 1511057,
          title: 'Compañeras de cuarto',
          original_title: 'Roommates',
          overview:
            'Cuando Devon, tímida y recién llegada a la uni, le pide a la popular Celeste compartir cuarto, su nueva amistad se convierte en una guerra de pasivoagresividad.',
          poster_path: '/hHOBxFzUK2CHmQ5djuOneyHkptS.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [35],
          popularity: 66.8245,
          release_date: '2026-04-13',
          video: false,
          vote_average: 6.466,
          vote_count: 29,
        },
        {
          adult: false,
          backdrop_path: '/jJmlCFi5EjpH5vHmOczRiVDm0qS.jpg',
          id: 1613798,
          title: 'Venganza',
          original_title: 'Venganza',
          overview: '',
          poster_path: '/ggJGx8fwwy21gEIXYusIlHcUn8z.jpg',
          media_type: 'movie',
          original_language: 'es',
          genre_ids: [28, 53],
          popularity: 76.1661,
          release_date: '2026-02-26',
          video: false,
          vote_average: 6.263,
          vote_count: 19,
        },
        {
          adult: false,
          backdrop_path: '/6Lm7CtE0AM7FLsHagrvZJCxtgzm.jpg',
          id: 1674749,
          title: 'WWE WrestleMania 42 - Saturday',
          original_title: 'WWE WrestleMania 42 - Saturday',
          overview: '',
          poster_path: '/3ZqaqAmOusw3f2bN164niCFWqgx.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [28, 18, 35],
          popularity: 0.9975,
          release_date: '2026-04-18',
          video: false,
          vote_average: 5.3,
          vote_count: 7,
        },
        {
          adult: false,
          backdrop_path: '/iQSXJs6RbTumcwxMjCedDoK99rx.jpg',
          id: 1659087,
          title: '180',
          original_title: '180',
          overview:
            'Un inesperado incidente de tráfico deja a su hijo en estado crítico. El padre, enfurecido, se adentra en una oscura espiral de confusión emocional y venganza.',
          poster_path: '/9ISjrhA38HpSSGtfiCk8lpziC3K.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [53, 80, 18],
          popularity: 59.8316,
          release_date: '2026-04-16',
          video: false,
          vote_average: 5.321,
          vote_count: 14,
        },
        {
          adult: false,
          backdrop_path: '/jRsjWwZzI39bTm44FNhRtiICd9k.jpg',
          id: 1084577,
          title: 'Balls Up: Con un par',
          original_title: 'Balls Up',
          overview:
            'Los ejecutivos de marketing Brad y Elijah lanzan un audaz patrocinio de preservativos de cobertura total directamente a la Copa del Mundo. Después de que su ebria celebración en Brasil desencadene un escándalo mundial, deberán huir de hinchas furiosos, delincuentes y funcionarios sedientos de poder para salvar sus carreras y volver a casa con vida.',
          poster_path: '/50V1E3NE3UDFmq0fhMpByx1b4Ka.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [35, 28, 12],
          popularity: 203.8693,
          release_date: '2026-04-15',
          video: false,
          vote_average: 5.447,
          vote_count: 74,
        },
        {
          adult: false,
          backdrop_path: '/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg',
          id: 83533,
          title: 'Avatar: Fuego y ceniza',
          original_title: 'Avatar: Fire and Ash',
          overview:
            "Jake Sully y Neytiri enfrentan una nueva amenaza en Pandora: los Ash People, una tribu Na'vi violenta y sedienta de poder, liderada por la implacable Varang. Tras la devastadora guerra contra la RDA y la pérdida de su hijo mayor, la familia de Jake deberá luchar por su supervivencia y el futuro de Pandora en un conflicto que llevará a los personajes a sus límites emocionales y físicos. Con nuevos y antiguos aliados, esta épica visual y emocional redefine el destino de un mundo al borde del abismo.",
          poster_path: '/4n1U0Mwn7djux6VKNYDRWPgS2x6.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [878, 12, 14],
          popularity: 315.4011,
          release_date: '2025-12-17',
          video: false,
          vote_average: 7.372,
          vote_count: 2641,
        },
        {
          adult: false,
          backdrop_path: '/gCmfeKmEAZBP5gcXpiqb0gii9rS.jpg',
          id: 1198994,
          title: 'SEND HELP (Enviad ayuda)',
          original_title: 'Send Help',
          overview:
            'Después de que un accidente de avión deje varados en una isla remota a una competente empleada y a su insoportable jefe, ella deberá utilizar sus habilidades de supervivencia para mantenerlos a ambos con vida, a pesar de su difícil relación.',
          poster_path: '/qXZZtyzuTX3KMfSLssCR6J0mODd.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [27, 53, 35],
          popularity: 191.8247,
          release_date: '2026-01-22',
          video: false,
          vote_average: 7.031,
          vote_count: 1023,
        },
        {
          adult: false,
          backdrop_path: '/xBT0oNq6rsTFv4SxG5uGRIEOrq6.jpg',
          id: 936075,
          title: 'Michael',
          original_title: 'Michael',
          overview:
            'El viaje de Michael Jackson más allá de la música, desde el descubrimiento de su extraordinario talento como líder de los Jackson Five hasta convertirse en una visionaria estrella cuya ambición creativa despertó un incansable afán por consagrarse como el mayor icono de la industria del entretenimiento.',
          poster_path: '/2uK36ujoDXOfNiJ5Yp3raVprB51.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [10402, 18],
          popularity: 50.0502,
          release_date: '2026-04-22',
          video: false,
          vote_average: 7.5,
          vote_count: 5,
        },
        {
          adult: false,
          backdrop_path: '/jSxeFrFCajefwka3TTRY4k8XVEX.jpg',
          id: 1266127,
          title: 'Noche de bodas 2',
          original_title: 'Ready or Not: Here I Come',
          overview:
            'Momentos después de sobrevivir a un ataque de la familia Le Domas, Grace descubre que ha alcanzado el siguiente nivel del juego, y esta vez acompañada por su hermana Faith, con quien mantiene una relación distante. Grace tiene una oportunidad para sobrevivir, mantener con vida a su hermana y reclamar el Alto Trono del Consejo que controla el mundo. Cuatro familias rivales la persiguen para hacerse con el trono, y quien gane lo gobernará todo.',
          poster_path: '/nDXKMOLJuBUKhYmHAY9qJdikuAq.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [27, 35],
          popularity: 76.0164,
          release_date: '2026-03-19',
          video: false,
          vote_average: 6.981,
          vote_count: 233,
        },
        {
          adult: false,
          backdrop_path: '/3ooXDVaz4xHKtwe4lkmF1gNopOC.jpg',
          id: 1290417,
          title: 'Embestida',
          original_title: 'Thrash',
          overview:
            'Cuando un catastrófico huracán azota un pueblo costero, el nivel del mar sube rápidamente y sus habitantes deben sobrevivir a un montón de hambrientos tiburones.',
          poster_path: '/osYy4GDE4nr69MGTJxRaZlqU82S.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [27, 53],
          popularity: 212.0369,
          release_date: '2026-04-10',
          video: false,
          vote_average: 5.99,
          vote_count: 335,
        },
        {
          adult: false,
          backdrop_path: '/vG42HeYtoTFflqwP42wYD7tBuNr.jpg',
          id: 1171145,
          title: 'Ruta de escape',
          original_title: 'Crime 101',
          overview:
            'Davis es un escurridizo ladrón cuyos atracos de alto riesgo tienen desconcertada a la policía. Davis está planeando su mayor golpe, con la esperanza de que sea el último, cuando se cruza en su camino Sharon, una desilusionada ejecutiva de seguros con la que se ve obligado a trabajar, y Orman un ladrón rival, con métodos mucho más inquietantes que los de Davis. A medida que se acerca el golpe multimillonario, el implacable teniente Lubesnik, se acerca a la operación, aumentando considerablemente el riesgo de lo que está en juego y difuminando la línea entre cazador y presa. Pronto, cada uno tendrá que aceptar el coste de sus decisiones asumiendo que no hay vuelta atrás.',
          poster_path: '/oUF0tTmbwlfkhiYSU5nXJccr5K0.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [80, 53],
          popularity: 167.3887,
          release_date: '2026-02-11',
          video: false,
          vote_average: 6.99,
          vote_count: 721,
        },
        {
          adult: false,
          backdrop_path: '/u53UYu5XG2hNgWGvs3xGhAVzypl.jpg',
          id: 1327819,
          title: 'Hoppers',
          original_title: 'Hoppers',
          overview:
            'Una amante de los animales aprovecha la oportunidad de utilizar una tecnología que coloca su conciencia en un castor robótico, descubriendo misterios dentro del mundo animal que van más allá de lo que podría haber imaginado.',
          poster_path: '/4Z0E1W7YvQ0aVtgj7KKtktb9ukd.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [16, 10751, 878, 35, 12],
          popularity: 219.481,
          release_date: '2026-03-04',
          video: false,
          vote_average: 7.581,
          vote_count: 480,
        },
        {
          adult: false,
          backdrop_path: '/qXxFWyur7jFkg2aQgENcXuyYeHF.jpg',
          id: 1480387,
          title: 'undertone',
          original_title: 'undertone',
          overview:
            'Una presentadora de pódcast de terror se muda con su madre terminal. Cintas misteriosas sobre vivencias paranormales de una pareja embarazada reflejan su situación, enloqueciendo.',
          poster_path: '/2PFgFMnrdCPXWiZl1PUvky7Mo9D.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [27, 9648],
          popularity: 119.4522,
          release_date: '2026-03-12',
          video: false,
          vote_average: 6.62,
          vote_count: 72,
        },
        {
          adult: false,
          backdrop_path: '/5rxEnsgriw8z065q51lrvPKYmCL.jpg',
          id: 1367642,
          title: 'No te olvidaré',
          original_title: 'Reminders of Him',
          overview:
            'Cuando los abuelos y tutores de Diem se niegan categóricamente a permitir que la vea, Kenna descubre una compasión inesperada seguida de un sentimiento más profundo y real con Ledger, exjugador de la NFL y propietario de un bar local. A medida que su romance secreto va cobrando forma, surgen problemas para los dos, lo que llevará a Kenna a una situación sentimental desoladora y, en último término, a reavivar la esperanza de una segunda oportunidad.',
          poster_path: '/iPJ4V6o5PttdBmHoehdOtWqQ6gx.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [10749, 18],
          popularity: 64.1082,
          release_date: '2026-03-11',
          video: false,
          vote_average: 7.1,
          vote_count: 128,
        },
        {
          adult: false,
          backdrop_path: '/1oKLEA9JOhvaBwLpqjROisvWMy7.jpg',
          id: 1325734,
          title: 'El drama',
          original_title: 'The Drama',
          overview:
            'Una pareja, en los días previos a su boda, se enfrenta a una crisis cuando unas inesperadas revelaciones desbaratan lo que uno de ellos creía saber sobre el otro.',
          poster_path: '/IsyXDsvsNthbtdpM4qMwop1Gwo.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [10749, 35, 18],
          popularity: 48.929,
          release_date: '2026-03-26',
          video: false,
          vote_average: 7.033,
          vote_count: 456,
        },
        {
          adult: false,
          backdrop_path: '/hHDNOlATHhre4eZ7aYz5cdyJLik.jpg',
          id: 1272837,
          title: '28 años después: El templo de los huesos',
          original_title: '28 Years Later: The Bone Temple',
          overview:
            "El Dr. Kelson (Ralph Fiennes) se ve envuelto en una nueva y sorprendente relación, cuyas consecuencias podrían cambiar el mundo tal y como se conoce. Por otra parte, el encuentro de Spike (Alfie Williams) con el Gran Lord Jimmy Crystal (Jack O'Connell) se convierte en una pesadilla de la que el chico no puede escapar. En este mundo, los infectados ya no son la mayor amenaza para la supervivencia, ya que la inhumanidad de los supervivientes puede ser aún más extraña y aterradora.",
          poster_path: '/2DTPapravB7kVBWjm6RsqEWyNqn.jpg',
          media_type: 'movie',
          original_language: 'en',
          genre_ids: [27, 53, 878],
          popularity: 53.8672,
          release_date: '2026-01-14',
          video: false,
          vote_average: 7.151,
          vote_count: 1030,
        },
      ],
      total_pages: 500,
      total_results: 10000,
    };
    (global.fetch as jest.Mock).mockResolvedValue({
      ok: true,
      status: 200,
      json: async () => mockRes,
    });
    const res = await request(app).get('/api/movies/featured?language=es-AR&timeframe=day');

    expect(res.status).toBe(200);
    expect(res.body).toEqual([
      {
        id: 687163,
        title: 'Proyecto Salvación',
        overview:
          'El profesor de ciencias Ryland Grace se despierta en una nave espacial a años luz de casa sin recordar quién es ni cómo ha llegado hasta allí. A medida que recupera la memoria, empieza a descubrir su misión: resolver el enigma de la misteriosa sustancia que provoca la extinción del sol. Deberá recurrir a sus conocimientos científicos y a sus ideas poco ortodoxas para salvar todo lo que hay en la Tierra de la extinción... pero una amistad inesperada significa que quizá no tenga que hacerlo solo.',
        release_date: '2026-03-15',
        genre_ids: [878, 12],
        original_language: 'en',
        backdrop_path: '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
        poster_path: '/7lwOTxajURKEWO6gI370NTrVdBO.jpg',
      },
      {
        id: 1226863,
        title: 'Super Mario Galaxy la película',
        overview:
          "Secuela de 'Super Mario Bros: La película', basada en la saga 'Mario Galaxy'. Los hermanos Mario y Luigi y la princesa Peach emprenden una aventura hasta los confines del espacio y a través de la galaxia.",
        release_date: '2026-04-01',
        genre_ids: [10751, 35, 12, 14, 16],
        original_language: 'en',
        backdrop_path: '/9Z2uDYXqJrlmePznQQJhL6d92Rq.jpg',
        poster_path: '/79EVB4qhyfrdlMgT8GIRAikdzsQ.jpg',
      },
      {
        id: 980431,
        title: 'La leyenda de Aang: El último Airbender',
        overview:
          "Película de animación que seguirá a Aang y sus amigos, ahora como jóvenes adultos, varios años después de los acontecimientos del final de 'Avatar: The Last Airbender'.",
        release_date: '2026-10-09',
        genre_ids: [16, 28, 12, 14],
        original_language: 'en',
        backdrop_path: '/sS3zGYFPcfM5pArVNWl6qLyaSmU.jpg',
        poster_path: '/gPiyTLo5GGwtJl0L8TlaJF9r0KE.jpg',
      },
      {
        id: 1304313,
        title: 'La momia de Lee Cronin',
        overview:
          'La joven hija de un periodista desaparece en el desierto sin dejar rastro—ocho años más tarde, la familia rota se conmociona cuando ella es devuelta a ellos, y lo que debiera haber sido una reunión jubilosa se convierte en una auténtica pesadilla.',
        release_date: '2026-04-15',
        genre_ids: [27, 9648],
        original_language: 'en',
        backdrop_path: '/zc08qkHtWfZ2cQGQBK1S5yafJmR.jpg',
        poster_path: '/hGgSpTX2f3ShFD41Ul0vcY3DSHb.jpg',
      },
      {
        id: 1511057,
        title: 'Compañeras de cuarto',
        overview:
          'Cuando Devon, tímida y recién llegada a la uni, le pide a la popular Celeste compartir cuarto, su nueva amistad se convierte en una guerra de pasivoagresividad.',
        release_date: '2026-04-13',
        genre_ids: [35],
        original_language: 'en',
        backdrop_path: '/cW8iKmWA6JAHgvNMyvrjqWd1dNp.jpg',
        poster_path: '/hHOBxFzUK2CHmQ5djuOneyHkptS.jpg',
      },
      {
        id: 1613798,
        title: 'Venganza',
        overview: '',
        release_date: '2026-02-26',
        genre_ids: [28, 53],
        original_language: 'es',
        backdrop_path: '/jJmlCFi5EjpH5vHmOczRiVDm0qS.jpg',
        poster_path: '/ggJGx8fwwy21gEIXYusIlHcUn8z.jpg',
      },
      {
        id: 1674749,
        title: 'WWE WrestleMania 42 - Saturday',
        overview: '',
        release_date: '2026-04-18',
        genre_ids: [28, 18, 35],
        original_language: 'en',
        backdrop_path: '/6Lm7CtE0AM7FLsHagrvZJCxtgzm.jpg',
        poster_path: '/3ZqaqAmOusw3f2bN164niCFWqgx.jpg',
      },
      {
        id: 1659087,
        title: '180',
        overview:
          'Un inesperado incidente de tráfico deja a su hijo en estado crítico. El padre, enfurecido, se adentra en una oscura espiral de confusión emocional y venganza.',
        release_date: '2026-04-16',
        genre_ids: [53, 80, 18],
        original_language: 'en',
        backdrop_path: '/iQSXJs6RbTumcwxMjCedDoK99rx.jpg',
        poster_path: '/9ISjrhA38HpSSGtfiCk8lpziC3K.jpg',
      },
      {
        id: 1084577,
        title: 'Balls Up: Con un par',
        overview:
          'Los ejecutivos de marketing Brad y Elijah lanzan un audaz patrocinio de preservativos de cobertura total directamente a la Copa del Mundo. Después de que su ebria celebración en Brasil desencadene un escándalo mundial, deberán huir de hinchas furiosos, delincuentes y funcionarios sedientos de poder para salvar sus carreras y volver a casa con vida.',
        release_date: '2026-04-15',
        genre_ids: [35, 28, 12],
        original_language: 'en',
        backdrop_path: '/jRsjWwZzI39bTm44FNhRtiICd9k.jpg',
        poster_path: '/50V1E3NE3UDFmq0fhMpByx1b4Ka.jpg',
      },
      {
        id: 83533,
        title: 'Avatar: Fuego y ceniza',
        overview:
          "Jake Sully y Neytiri enfrentan una nueva amenaza en Pandora: los Ash People, una tribu Na'vi violenta y sedienta de poder, liderada por la implacable Varang. Tras la devastadora guerra contra la RDA y la pérdida de su hijo mayor, la familia de Jake deberá luchar por su supervivencia y el futuro de Pandora en un conflicto que llevará a los personajes a sus límites emocionales y físicos. Con nuevos y antiguos aliados, esta épica visual y emocional redefine el destino de un mundo al borde del abismo.",
        release_date: '2025-12-17',
        genre_ids: [878, 12, 14],
        original_language: 'en',
        backdrop_path: '/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg',
        poster_path: '/4n1U0Mwn7djux6VKNYDRWPgS2x6.jpg',
      },
      {
        id: 1198994,
        title: 'SEND HELP (Enviad ayuda)',
        overview:
          'Después de que un accidente de avión deje varados en una isla remota a una competente empleada y a su insoportable jefe, ella deberá utilizar sus habilidades de supervivencia para mantenerlos a ambos con vida, a pesar de su difícil relación.',
        release_date: '2026-01-22',
        genre_ids: [27, 53, 35],
        original_language: 'en',
        backdrop_path: '/gCmfeKmEAZBP5gcXpiqb0gii9rS.jpg',
        poster_path: '/qXZZtyzuTX3KMfSLssCR6J0mODd.jpg',
      },
      {
        id: 936075,
        title: 'Michael',
        overview:
          'El viaje de Michael Jackson más allá de la música, desde el descubrimiento de su extraordinario talento como líder de los Jackson Five hasta convertirse en una visionaria estrella cuya ambición creativa despertó un incansable afán por consagrarse como el mayor icono de la industria del entretenimiento.',
        release_date: '2026-04-22',
        genre_ids: [10402, 18],
        original_language: 'en',
        backdrop_path: '/xBT0oNq6rsTFv4SxG5uGRIEOrq6.jpg',
        poster_path: '/2uK36ujoDXOfNiJ5Yp3raVprB51.jpg',
      },
      {
        id: 1266127,
        title: 'Noche de bodas 2',
        overview:
          'Momentos después de sobrevivir a un ataque de la familia Le Domas, Grace descubre que ha alcanzado el siguiente nivel del juego, y esta vez acompañada por su hermana Faith, con quien mantiene una relación distante. Grace tiene una oportunidad para sobrevivir, mantener con vida a su hermana y reclamar el Alto Trono del Consejo que controla el mundo. Cuatro familias rivales la persiguen para hacerse con el trono, y quien gane lo gobernará todo.',
        release_date: '2026-03-19',
        genre_ids: [27, 35],
        original_language: 'en',
        backdrop_path: '/jSxeFrFCajefwka3TTRY4k8XVEX.jpg',
        poster_path: '/nDXKMOLJuBUKhYmHAY9qJdikuAq.jpg',
      },
      {
        id: 1290417,
        title: 'Embestida',
        overview:
          'Cuando un catastrófico huracán azota un pueblo costero, el nivel del mar sube rápidamente y sus habitantes deben sobrevivir a un montón de hambrientos tiburones.',
        release_date: '2026-04-10',
        genre_ids: [27, 53],
        original_language: 'en',
        backdrop_path: '/3ooXDVaz4xHKtwe4lkmF1gNopOC.jpg',
        poster_path: '/osYy4GDE4nr69MGTJxRaZlqU82S.jpg',
      },
      {
        id: 1171145,
        title: 'Ruta de escape',
        overview:
          'Davis es un escurridizo ladrón cuyos atracos de alto riesgo tienen desconcertada a la policía. Davis está planeando su mayor golpe, con la esperanza de que sea el último, cuando se cruza en su camino Sharon, una desilusionada ejecutiva de seguros con la que se ve obligado a trabajar, y Orman un ladrón rival, con métodos mucho más inquietantes que los de Davis. A medida que se acerca el golpe multimillonario, el implacable teniente Lubesnik, se acerca a la operación, aumentando considerablemente el riesgo de lo que está en juego y difuminando la línea entre cazador y presa. Pronto, cada uno tendrá que aceptar el coste de sus decisiones asumiendo que no hay vuelta atrás.',
        release_date: '2026-02-11',
        genre_ids: [80, 53],
        original_language: 'en',
        backdrop_path: '/vG42HeYtoTFflqwP42wYD7tBuNr.jpg',
        poster_path: '/oUF0tTmbwlfkhiYSU5nXJccr5K0.jpg',
      },
      {
        id: 1327819,
        title: 'Hoppers',
        overview:
          'Una amante de los animales aprovecha la oportunidad de utilizar una tecnología que coloca su conciencia en un castor robótico, descubriendo misterios dentro del mundo animal que van más allá de lo que podría haber imaginado.',
        release_date: '2026-03-04',
        genre_ids: [16, 10751, 878, 35, 12],
        original_language: 'en',
        backdrop_path: '/u53UYu5XG2hNgWGvs3xGhAVzypl.jpg',
        poster_path: '/4Z0E1W7YvQ0aVtgj7KKtktb9ukd.jpg',
      },
      {
        id: 1480387,
        title: 'undertone',
        overview:
          'Una presentadora de pódcast de terror se muda con su madre terminal. Cintas misteriosas sobre vivencias paranormales de una pareja embarazada reflejan su situación, enloqueciendo.',
        release_date: '2026-03-12',
        genre_ids: [27, 9648],
        original_language: 'en',
        backdrop_path: '/qXxFWyur7jFkg2aQgENcXuyYeHF.jpg',
        poster_path: '/2PFgFMnrdCPXWiZl1PUvky7Mo9D.jpg',
      },
      {
        id: 1367642,
        title: 'No te olvidaré',
        overview:
          'Cuando los abuelos y tutores de Diem se niegan categóricamente a permitir que la vea, Kenna descubre una compasión inesperada seguida de un sentimiento más profundo y real con Ledger, exjugador de la NFL y propietario de un bar local. A medida que su romance secreto va cobrando forma, surgen problemas para los dos, lo que llevará a Kenna a una situación sentimental desoladora y, en último término, a reavivar la esperanza de una segunda oportunidad.',
        release_date: '2026-03-11',
        genre_ids: [10749, 18],
        original_language: 'en',
        backdrop_path: '/5rxEnsgriw8z065q51lrvPKYmCL.jpg',
        poster_path: '/iPJ4V6o5PttdBmHoehdOtWqQ6gx.jpg',
      },
      {
        id: 1325734,
        title: 'El drama',
        overview:
          'Una pareja, en los días previos a su boda, se enfrenta a una crisis cuando unas inesperadas revelaciones desbaratan lo que uno de ellos creía saber sobre el otro.',
        release_date: '2026-03-26',
        genre_ids: [10749, 35, 18],
        original_language: 'en',
        backdrop_path: '/1oKLEA9JOhvaBwLpqjROisvWMy7.jpg',
        poster_path: '/IsyXDsvsNthbtdpM4qMwop1Gwo.jpg',
      },
      {
        id: 1272837,
        title: '28 años después: El templo de los huesos',
        overview:
          "El Dr. Kelson (Ralph Fiennes) se ve envuelto en una nueva y sorprendente relación, cuyas consecuencias podrían cambiar el mundo tal y como se conoce. Por otra parte, el encuentro de Spike (Alfie Williams) con el Gran Lord Jimmy Crystal (Jack O'Connell) se convierte en una pesadilla de la que el chico no puede escapar. En este mundo, los infectados ya no son la mayor amenaza para la supervivencia, ya que la inhumanidad de los supervivientes puede ser aún más extraña y aterradora.",
        release_date: '2026-01-14',
        genre_ids: [27, 53, 878],
        original_language: 'en',
        backdrop_path: '/hHDNOlATHhre4eZ7aYz5cdyJLik.jpg',
        poster_path: '/2DTPapravB7kVBWjm6RsqEWyNqn.jpg',
      },
    ]);
  });
});

describe('Get featured with missing api key', () => {
  it('Handles a missing API key', async () => {
    delete process.env.TMDB_API_KEY;
    const res = await request(app).get('/api/movies/featured');

    expect(res.status).toBe(500);
  });
});

describe('Get featured when no tmdb response', () => {
  it('Handles TMDB not responding', async () => {
    const res = await request(app).get('/api/movies/featured');

    expect(res.status).toBe(502);
  });
});
