import request from 'supertest';
import { app } from '../src/app';

beforeAll(() => {
  process.env.NODE_ENV = 'test';
});

beforeEach(() => {
  process.env.TMDB_API_KEY = 'TEST API KEY';
  global.fetch = jest.fn();
});

afterEach(() => {
  delete process.env.TMDB_API_KEY;
  jest.restoreAllMocks();
});

describe('Get featured shows', () => {
  it('GET /api/tv/featured should return featured shows', async () => {
    const mockResult = {
      page: 1,
      results: [
        {
          adult: false,
          backdrop_path: '/GN2KFXiHPVV6sIw4v2P2pqCJty.jpg',
          id: 85552,
          name: 'Euphoria',
          original_name: 'Euphoria',
          overview:
            'A group of high school students navigate love and friendships in a world of drugs, sex, trauma, and social media.',
          poster_path: '/aJrG7OkoTMPWG5c8opz8a93AZPY.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [18],
          popularity: 394.5648,
          first_air_date: '2019-06-16',
          vote_average: 8.3,
          vote_count: 10407,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/bq28ajZaoMyzEIm6REelqyqtEDZ.jpg',
          id: 76479,
          name: 'The Boys',
          original_name: 'The Boys',
          overview:
            'A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.',
          poster_path: '/in1R2dDc421JxsoRWaIIAqVI2KE.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [10765, 10759],
          popularity: 646.578,
          first_air_date: '2019-07-25',
          vote_average: 8.44,
          vote_count: 11904,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
          id: 37854,
          name: 'One Piece',
          original_name: 'ワンピース',
          overview:
            'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n' +
            '\n' +
            `Monkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he's surrounded by a bevy of skilled fighters and thieves to help him along the way.\n` +
            '\n' +
            'Luffy will do anything to get the One Piece and become King of the Pirates!',
          poster_path: '/uiIB9ctqZFbfRXXimtpmZb5dusi.jpg',
          media_type: 'tv',
          original_language: 'ja',
          genre_ids: [10759, 35, 16],
          popularity: 47.468,
          first_air_date: '1999-10-20',
          vote_average: 8.725,
          vote_count: 5218,
          origin_country: ['JP'],
        },
        {
          adult: false,
          backdrop_path: '/6gN8DYnIEln8v7OhRy61c57w0Xy.jpg',
          id: 124364,
          name: 'FROM',
          original_name: 'FROM',
          overview:
            'Unravel the mystery of a nightmarish town in middle America that traps all those who enter. As the unwilling residents fight to keep a sense of normalcy and search for a way out, they must also survive the threats of the surrounding forest – including the terrifying creatures that come out when the sun goes down.',
          poster_path: '/cjXLrg4R7FRPFafvuQ3SSznQOd9.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [9648, 18, 10765],
          popularity: 175.2807,
          first_air_date: '2022-02-20',
          vote_average: 8.163,
          vote_count: 2561,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/z3BkMbCy5ajZPMyKEUwsPHuz2cV.jpg',
          id: 250307,
          name: 'The Pitt',
          original_name: 'The Pitt',
          overview:
            "The staff of Pittsburgh's Trauma Medical Center work around the clock to save lives in an overcrowded and underfunded emergency department.",
          poster_path: '/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [18],
          popularity: 142.1153,
          first_air_date: '2025-01-09',
          vote_average: 8.7,
          vote_count: 649,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/9qrroces8C6R9aKr08hACNPVXdZ.jpg',
          id: 95557,
          name: 'INVINCIBLE',
          original_name: 'INVINCIBLE',
          overview:
            "Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own and enters into his father's tutelage.",
          poster_path: '/4tblBrslcKSifMVZ3TmtT2ukMor.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [16, 18, 10765, 10759],
          popularity: 238.8614,
          first_air_date: '2021-03-25',
          vote_average: 8.6,
          vote_count: 5567,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/qrTAc0ZtQ859Qu5O8cixJzNJpQs.jpg',
          id: 202555,
          name: 'Daredevil: Born Again',
          original_name: 'Daredevil: Born Again',
          overview:
            'Matt Murdock, a blind lawyer with heightened abilities, is fighting for justice through his bustling law firm, while former mob boss Wilson Fisk pursues his own political endeavors in New York. When their past identities begin to emerge, both men find themselves on an inevitable collision course.',
          poster_path: '/xDUoAsU8lQHOOoRkFiBuarmACDN.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [18, 10759, 80],
          popularity: 95.1212,
          first_air_date: '2025-03-04',
          vote_average: 8,
          vote_count: 751,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/2VHbof9yaNhovEnaancBkXEULCT.jpg',
          id: 154385,
          name: 'BEEF',
          original_name: 'BEEF',
          overview:
            'A road rage incident between two strangers — a failing contractor and an unfulfilled entrepreneur — sparks a feud that brings out their darkest impulses.',
          poster_path: '/25ih0Xq2zWbxhhKxwhvswKYQyEr.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [35, 18],
          popularity: 70.9801,
          first_air_date: '2023-04-06',
          vote_average: 7.8,
          vote_count: 893,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/uekZzyLReK777QKO9xKwiPOelCQ.jpg',
          id: 279471,
          name: "Malcolm in the Middle: Life's Still Unfair",
          original_name: "Malcolm in the Middle: Life's Still Unfair",
          overview:
            'After shielding himself and his daughter from his family for over a decade, Malcolm is dragged back into their orbit when Hal and Lois demand his presence at their 40th anniversary party.',
          poster_path: '/4uXAZRYtcMfoX2XtY1gcUxLHhjj.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [35, 18],
          popularity: 139.7337,
          first_air_date: '2026-04-10',
          vote_average: 8.1,
          vote_count: 230,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg',
          id: 209867,
          name: "Frieren: Beyond Journey's End",
          original_name: '葬送のフリーレン',
          overview:
            "Decades after her party defeated the Demon King, an old friend's funeral launches the elf wizard Frieren on a journey of self-discovery.",
          poster_path: '/dqZENchTd7lp5zht7BdlqM7RBhD.jpg',
          media_type: 'tv',
          original_language: 'ja',
          genre_ids: [16, 10759, 18, 10765],
          popularity: 85.9914,
          first_air_date: '2023-09-29',
          vote_average: 8.806,
          vote_count: 780,
          origin_country: ['JP'],
        },
        {
          adult: false,
          backdrop_path: '/qpin8cASXEVtwhzNsprHYFiOAGk.jpg',
          id: 95479,
          name: 'JUJUTSU KAISEN',
          original_name: '呪術廻戦',
          overview:
            'Yuji Itadori is a boy with tremendous physical strength, though he lives a completely ordinary high school life. One day, to save a classmate who has been attacked by curses, he eats the finger of Ryomen Sukuna, taking the curse into his own soul. From then on, he shares one body with Ryomen Sukuna. Guided by the most powerful of sorcerers, Satoru Gojo, Itadori is admitted to Tokyo Jujutsu High School, an organization that fights the curses... and thus begins the heroic tale of a boy who became a curse to exorcise a curse, a life from which he could never turn back.',
          poster_path: '/6qQzMJG27XOJsyAEEIisoJB45j2.jpg',
          media_type: 'tv',
          original_language: 'ja',
          genre_ids: [16, 10759, 10765],
          popularity: 155.3905,
          first_air_date: '2020-10-03',
          vote_average: 8.558,
          vote_count: 4325,
          origin_country: ['JP'],
        },
        {
          adult: false,
          backdrop_path: '/x6y59dJBE1o0r4YRsWVQXE2nnlB.jpg',
          id: 65942,
          name: 'Re:ZERO -Starting Life in Another World-',
          original_name: 'Re:ゼロから始める異世界生活',
          overview:
            "Natsuki Subaru, an ordinary high school  student, is on his way home from the convenience store when he finds  himself transported to another world. As he's lost and confused in a new  world where he doesn't even know left from right, the only person to  reach out to him was a beautiful girl with silver hair. Determined to  repay her somehow for saving him from his own despair, Subaru agrees to  help the girl find something she's looking for.",
          poster_path: '/aRwmcX36r1ZpR5Xq5mmFcpUDQ8J.jpg',
          media_type: 'tv',
          original_language: 'ja',
          genre_ids: [16, 10759, 10765, 9648],
          popularity: 53.711,
          first_air_date: '2016-04-04',
          vote_average: 7.846,
          vote_count: 599,
          origin_country: ['JP'],
        },
        {
          adult: false,
          backdrop_path: '/7IY4wELVMvtUc78vPiuL8kQV2iA.jpg',
          id: 202411,
          name: 'Monarch: Legacy of Monsters',
          original_name: 'Monarch: Legacy of Monsters',
          overview:
            "After surviving Godzilla's attack on San Francisco, Cate is shaken yet again by a shocking secret. Amid monstrous threats, she embarks on a globetrotting adventure to learn the truth about her family—and the mysterious organization known as Monarch.",
          poster_path: '/7LBbaEaLSbqdviBYaSS1rRPMnrs.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [10765, 18, 10759],
          popularity: 125.8214,
          first_air_date: '2023-11-16',
          vote_average: 7.704,
          vote_count: 1159,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/qD211Hb5XwFxrszzBBe5EUYJerh.jpg',
          id: 111110,
          name: 'ONE PIECE',
          original_name: 'ONE PIECE',
          overview:
            'With his straw hat and ragtag crew, young pirate Monkey D. Luffy goes on an epic voyage for treasure.',
          poster_path: '/blWCPEqDGLBuLB9u89CxP9ORQP4.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [10759, 10765],
          popularity: 59.5421,
          first_air_date: '2023-08-31',
          vote_average: 8.117,
          vote_count: 1711,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/kz1ceDJ7e8z8zIQNURJcGOoQ8WY.jpg',
          id: 295778,
          name: 'Scrubs',
          original_name: 'Scrubs',
          overview:
            'J.D. & Turk scrub in together for the first time in a long time–medicine has changed, interns have changed, but their bromance has stood the test of time. Characters new and old navigate the waters of Sacred Heart with laughter, heart and some surprises along the way.',
          poster_path: '/nNNM50G7p9C3n4vgidCiybsIdHA.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [35],
          popularity: 31.5206,
          first_air_date: '2026-02-25',
          vote_average: 8.155,
          vote_count: 42,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/5SrsdKcN9Flvccq59sIfJbhq1Fk.jpg',
          id: 289219,
          name: 'Star Wars: Maul - Shadow Lord',
          original_name: 'Star Wars: Maul - Shadow Lord',
          overview:
            'After the Clone Wars, Maul plots to rebuild his criminal syndicate on a planet untouched by the Empire.',
          poster_path: '/fTfLd3s9yBNOzbFHD2aXvwEs93H.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [16, 10765, 10759],
          popularity: 46.7935,
          first_air_date: '2026-04-06',
          vote_average: 7.64,
          vote_count: 43,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/yZjaZJSW2Fbm4Hi1Y8p8f4FGCJw.jpg',
          id: 245318,
          name: "Margo's Got Money Troubles",
          original_name: "Margo's Got Money Troubles",
          overview:
            "The daughter of a former Hooter's waitress and an ex-pro wrestler, Margo is a recent college dropout and aspiring writer. Faced with a new baby, mounting pile of bills, and dwindling number of ways to pay them, Margo must find a way forward.",
          poster_path: '/5iVWUVfxOS1JFudntvPcLyHBw9y.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [18, 35],
          popularity: 108.8908,
          first_air_date: '2026-04-14',
          vote_average: 8.208,
          vote_count: 12,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/5QsLvWh8J1mXl1W05wNJknMmhzR.jpg',
          id: 245927,
          name: 'Paradise',
          original_name: 'Paradise',
          overview:
            "The tranquility in a serene, wealthy community inhabited by some of the world's most prominent individuals explodes when a shocking murder occurs and a high stakes investigation unfolds.",
          poster_path: '/l8RqfhqEk04W5sSOjQ9zeWU1DyM.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [80, 18],
          popularity: 52.0111,
          first_air_date: '2025-01-26',
          vote_average: 7.448,
          vote_count: 420,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/6iNWfGVCEfASDdlNb05TP5nG0ll.jpg',
          id: 79744,
          name: 'The Rookie',
          original_name: 'The Rookie',
          overview:
            "Starting over isn't easy, especially for small-town guy John Nolan who, after a life-altering incident, is pursuing his dream of being an LAPD officer. As the force's oldest rookie, he's met with skepticism from some higher-ups who see him as just a walking midlife crisis.",
          poster_path: '/70kTz0OmjjZe7zHvIDrq2iKW7PJ.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [80, 18, 35],
          popularity: 266.5502,
          first_air_date: '2018-10-16',
          vote_average: 8.5,
          vote_count: 3115,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/4X86dOxMsrZudL0PdsMv30NGBWZ.jpg',
          id: 258036,
          name: 'The Audacity',
          original_name: 'The Audacity',
          overview:
            'Inside the bubble of Silicon Valley, a data-mining CEO strives to turn insight and influence into profit and power in this darkly comedic look at the warped dreams, outsized egos, and ethical lapses of the self-styled inventors of the future.',
          poster_path: '/ea6hHjW8yWjROSYwynpWsYc4mYZ.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [18, 35],
          popularity: 44.8409,
          first_air_date: '2026-04-05',
          vote_average: 7.2,
          vote_count: 4,
          origin_country: ['US'],
        },
      ],
      total_pages: 500,
      total_results: 10000,
    };

    (global.fetch as jest.Mock).mockResolvedValue({
      ok: true,
      status: 200,
      json: async () => mockResult,
    });
    const res = await request(app).get('/api/tv/featured');

    expect(res.status).toBe(200);
    expect(res.body).toEqual([
      {
        id: 85552,
        name: 'Euphoria',
        overview:
          'A group of high school students navigate love and friendships in a world of drugs, sex, trauma, and social media.',
        first_air_date: '2019-06-16',
        genre_ids: [18],
        original_language: 'en',
        backdrop_path: '/GN2KFXiHPVV6sIw4v2P2pqCJty.jpg',
        poster_path: '/aJrG7OkoTMPWG5c8opz8a93AZPY.jpg',
      },
      {
        id: 76479,
        name: 'The Boys',
        overview:
          'A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.',
        first_air_date: '2019-07-25',
        genre_ids: [10765, 10759],
        original_language: 'en',
        backdrop_path: '/bq28ajZaoMyzEIm6REelqyqtEDZ.jpg',
        poster_path: '/in1R2dDc421JxsoRWaIIAqVI2KE.jpg',
      },
      {
        id: 37854,
        name: 'One Piece',
        overview:
          'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
        first_air_date: '1999-10-20',
        genre_ids: [10759, 35, 16],
        original_language: 'ja',
        backdrop_path: '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
        poster_path: '/uiIB9ctqZFbfRXXimtpmZb5dusi.jpg',
      },
      {
        id: 124364,
        name: 'FROM',
        overview:
          'Unravel the mystery of a nightmarish town in middle America that traps all those who enter. As the unwilling residents fight to keep a sense of normalcy and search for a way out, they must also survive the threats of the surrounding forest – including the terrifying creatures that come out when the sun goes down.',
        first_air_date: '2022-02-20',
        genre_ids: [9648, 18, 10765],
        original_language: 'en',
        backdrop_path: '/6gN8DYnIEln8v7OhRy61c57w0Xy.jpg',
        poster_path: '/cjXLrg4R7FRPFafvuQ3SSznQOd9.jpg',
      },
      {
        id: 250307,
        name: 'The Pitt',
        overview:
          "The staff of Pittsburgh's Trauma Medical Center work around the clock to save lives in an overcrowded and underfunded emergency department.",
        first_air_date: '2025-01-09',
        genre_ids: [18],
        original_language: 'en',
        backdrop_path: '/z3BkMbCy5ajZPMyKEUwsPHuz2cV.jpg',
        poster_path: '/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg',
      },
      {
        id: 95557,
        name: 'INVINCIBLE',
        overview:
          "Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own and enters into his father's tutelage.",
        first_air_date: '2021-03-25',
        genre_ids: [16, 18, 10765, 10759],
        original_language: 'en',
        backdrop_path: '/9qrroces8C6R9aKr08hACNPVXdZ.jpg',
        poster_path: '/4tblBrslcKSifMVZ3TmtT2ukMor.jpg',
      },
      {
        id: 202555,
        name: 'Daredevil: Born Again',
        overview:
          'Matt Murdock, a blind lawyer with heightened abilities, is fighting for justice through his bustling law firm, while former mob boss Wilson Fisk pursues his own political endeavors in New York. When their past identities begin to emerge, both men find themselves on an inevitable collision course.',
        first_air_date: '2025-03-04',
        genre_ids: [18, 10759, 80],
        original_language: 'en',
        backdrop_path: '/qrTAc0ZtQ859Qu5O8cixJzNJpQs.jpg',
        poster_path: '/xDUoAsU8lQHOOoRkFiBuarmACDN.jpg',
      },
      {
        id: 154385,
        name: 'BEEF',
        overview:
          'A road rage incident between two strangers — a failing contractor and an unfulfilled entrepreneur — sparks a feud that brings out their darkest impulses.',
        first_air_date: '2023-04-06',
        genre_ids: [35, 18],
        original_language: 'en',
        backdrop_path: '/2VHbof9yaNhovEnaancBkXEULCT.jpg',
        poster_path: '/25ih0Xq2zWbxhhKxwhvswKYQyEr.jpg',
      },
      {
        id: 279471,
        name: "Malcolm in the Middle: Life's Still Unfair",
        overview:
          'After shielding himself and his daughter from his family for over a decade, Malcolm is dragged back into their orbit when Hal and Lois demand his presence at their 40th anniversary party.',
        first_air_date: '2026-04-10',
        genre_ids: [35, 18],
        original_language: 'en',
        backdrop_path: '/uekZzyLReK777QKO9xKwiPOelCQ.jpg',
        poster_path: '/4uXAZRYtcMfoX2XtY1gcUxLHhjj.jpg',
      },
      {
        id: 209867,
        name: "Frieren: Beyond Journey's End",
        overview:
          "Decades after her party defeated the Demon King, an old friend's funeral launches the elf wizard Frieren on a journey of self-discovery.",
        first_air_date: '2023-09-29',
        genre_ids: [16, 10759, 18, 10765],
        original_language: 'ja',
        backdrop_path: '/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg',
        poster_path: '/dqZENchTd7lp5zht7BdlqM7RBhD.jpg',
      },
      {
        id: 95479,
        name: 'JUJUTSU KAISEN',
        overview:
          'Yuji Itadori is a boy with tremendous physical strength, though he lives a completely ordinary high school life. One day, to save a classmate who has been attacked by curses, he eats the finger of Ryomen Sukuna, taking the curse into his own soul. From then on, he shares one body with Ryomen Sukuna. Guided by the most powerful of sorcerers, Satoru Gojo, Itadori is admitted to Tokyo Jujutsu High School, an organization that fights the curses... and thus begins the heroic tale of a boy who became a curse to exorcise a curse, a life from which he could never turn back.',
        first_air_date: '2020-10-03',
        genre_ids: [16, 10759, 10765],
        original_language: 'ja',
        backdrop_path: '/qpin8cASXEVtwhzNsprHYFiOAGk.jpg',
        poster_path: '/6qQzMJG27XOJsyAEEIisoJB45j2.jpg',
      },
      {
        id: 65942,
        name: 'Re:ZERO -Starting Life in Another World-',
        overview:
          "Natsuki Subaru, an ordinary high school  student, is on his way home from the convenience store when he finds  himself transported to another world. As he's lost and confused in a new  world where he doesn't even know left from right, the only person to  reach out to him was a beautiful girl with silver hair. Determined to  repay her somehow for saving him from his own despair, Subaru agrees to  help the girl find something she's looking for.",
        first_air_date: '2016-04-04',
        genre_ids: [16, 10759, 10765, 9648],
        original_language: 'ja',
        backdrop_path: '/x6y59dJBE1o0r4YRsWVQXE2nnlB.jpg',
        poster_path: '/aRwmcX36r1ZpR5Xq5mmFcpUDQ8J.jpg',
      },
      {
        id: 202411,
        name: 'Monarch: Legacy of Monsters',
        overview:
          "After surviving Godzilla's attack on San Francisco, Cate is shaken yet again by a shocking secret. Amid monstrous threats, she embarks on a globetrotting adventure to learn the truth about her family—and the mysterious organization known as Monarch.",
        first_air_date: '2023-11-16',
        genre_ids: [10765, 18, 10759],
        original_language: 'en',
        backdrop_path: '/7IY4wELVMvtUc78vPiuL8kQV2iA.jpg',
        poster_path: '/7LBbaEaLSbqdviBYaSS1rRPMnrs.jpg',
      },
      {
        id: 111110,
        name: 'ONE PIECE',
        overview:
          'With his straw hat and ragtag crew, young pirate Monkey D. Luffy goes on an epic voyage for treasure.',
        first_air_date: '2023-08-31',
        genre_ids: [10759, 10765],
        original_language: 'en',
        backdrop_path: '/qD211Hb5XwFxrszzBBe5EUYJerh.jpg',
        poster_path: '/blWCPEqDGLBuLB9u89CxP9ORQP4.jpg',
      },
      {
        id: 295778,
        name: 'Scrubs',
        overview:
          'J.D. & Turk scrub in together for the first time in a long time–medicine has changed, interns have changed, but their bromance has stood the test of time. Characters new and old navigate the waters of Sacred Heart with laughter, heart and some surprises along the way.',
        first_air_date: '2026-02-25',
        genre_ids: [35],
        original_language: 'en',
        backdrop_path: '/kz1ceDJ7e8z8zIQNURJcGOoQ8WY.jpg',
        poster_path: '/nNNM50G7p9C3n4vgidCiybsIdHA.jpg',
      },
      {
        id: 289219,
        name: 'Star Wars: Maul - Shadow Lord',
        overview:
          'After the Clone Wars, Maul plots to rebuild his criminal syndicate on a planet untouched by the Empire.',
        first_air_date: '2026-04-06',
        genre_ids: [16, 10765, 10759],
        original_language: 'en',
        backdrop_path: '/5SrsdKcN9Flvccq59sIfJbhq1Fk.jpg',
        poster_path: '/fTfLd3s9yBNOzbFHD2aXvwEs93H.jpg',
      },
      {
        id: 245318,
        name: "Margo's Got Money Troubles",
        overview:
          "The daughter of a former Hooter's waitress and an ex-pro wrestler, Margo is a recent college dropout and aspiring writer. Faced with a new baby, mounting pile of bills, and dwindling number of ways to pay them, Margo must find a way forward.",
        first_air_date: '2026-04-14',
        genre_ids: [18, 35],
        original_language: 'en',
        backdrop_path: '/yZjaZJSW2Fbm4Hi1Y8p8f4FGCJw.jpg',
        poster_path: '/5iVWUVfxOS1JFudntvPcLyHBw9y.jpg',
      },
      {
        id: 245927,
        name: 'Paradise',
        overview:
          "The tranquility in a serene, wealthy community inhabited by some of the world's most prominent individuals explodes when a shocking murder occurs and a high stakes investigation unfolds.",
        first_air_date: '2025-01-26',
        genre_ids: [80, 18],
        original_language: 'en',
        backdrop_path: '/5QsLvWh8J1mXl1W05wNJknMmhzR.jpg',
        poster_path: '/l8RqfhqEk04W5sSOjQ9zeWU1DyM.jpg',
      },
      {
        id: 79744,
        name: 'The Rookie',
        overview:
          "Starting over isn't easy, especially for small-town guy John Nolan who, after a life-altering incident, is pursuing his dream of being an LAPD officer. As the force's oldest rookie, he's met with skepticism from some higher-ups who see him as just a walking midlife crisis.",
        first_air_date: '2018-10-16',
        genre_ids: [80, 18, 35],
        original_language: 'en',
        backdrop_path: '/6iNWfGVCEfASDdlNb05TP5nG0ll.jpg',
        poster_path: '/70kTz0OmjjZe7zHvIDrq2iKW7PJ.jpg',
      },
      {
        id: 258036,
        name: 'The Audacity',
        overview:
          'Inside the bubble of Silicon Valley, a data-mining CEO strives to turn insight and influence into profit and power in this darkly comedic look at the warped dreams, outsized egos, and ethical lapses of the self-styled inventors of the future.',
        first_air_date: '2026-04-05',
        genre_ids: [18, 35],
        original_language: 'en',
        backdrop_path: '/4X86dOxMsrZudL0PdsMv30NGBWZ.jpg',
        poster_path: '/ea6hHjW8yWjROSYwynpWsYc4mYZ.jpg',
      },
    ]);
  });
});

describe('Get featured with custom timeframe', () => {
  it('Returns a different set of data for 1 day', async () => {
    const mockRes = {
      page: 1,
      results: [
        {
          adult: false,
          backdrop_path: '/6gN8DYnIEln8v7OhRy61c57w0Xy.jpg',
          id: 124364,
          name: 'FROM',
          original_name: 'FROM',
          overview:
            'Unravel the mystery of a nightmarish town in middle America that traps all those who enter. As the unwilling residents fight to keep a sense of normalcy and search for a way out, they must also survive the threats of the surrounding forest – including the terrifying creatures that come out when the sun goes down.',
          poster_path: '/cjXLrg4R7FRPFafvuQ3SSznQOd9.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [9648, 18, 10765],
          popularity: 175.2807,
          first_air_date: '2022-02-20',
          vote_average: 8.163,
          vote_count: 2561,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/GN2KFXiHPVV6sIw4v2P2pqCJty.jpg',
          id: 85552,
          name: 'Euphoria',
          original_name: 'Euphoria',
          overview:
            'A group of high school students navigate love and friendships in a world of drugs, sex, trauma, and social media.',
          poster_path: '/aJrG7OkoTMPWG5c8opz8a93AZPY.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [18],
          popularity: 394.5648,
          first_air_date: '2019-06-16',
          vote_average: 8.3,
          vote_count: 10407,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/bq28ajZaoMyzEIm6REelqyqtEDZ.jpg',
          id: 76479,
          name: 'The Boys',
          original_name: 'The Boys',
          overview:
            'A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.',
          poster_path: '/in1R2dDc421JxsoRWaIIAqVI2KE.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [10765, 10759],
          popularity: 646.578,
          first_air_date: '2019-07-25',
          vote_average: 8.44,
          vote_count: 11904,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/4ZXZi107TbfBJFGT4cnqbavQIoc.jpg',
          id: 289424,
          name: 'We Are All Trying Here',
          original_name: '모두가 자신의 무가치함과 싸우고 있다',
          overview:
            'An aspiring director hits rock bottom after 20 years chasing his debut — until he meets an overwhelmed producer who helps him rediscover his self-worth.',
          poster_path: '/c2jswCrMoqDEBEXwSAlrCWtXdfZ.jpg',
          media_type: 'tv',
          original_language: 'ko',
          genre_ids: [18],
          popularity: 16.094,
          first_air_date: '2026-04-18',
          vote_average: 0,
          vote_count: 0,
          origin_country: ['KR'],
        },
        {
          adult: false,
          backdrop_path: '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
          id: 37854,
          name: 'One Piece',
          original_name: 'ワンピース',
          overview:
            'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n' +
            '\n' +
            `Monkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he's surrounded by a bevy of skilled fighters and thieves to help him along the way.\n` +
            '\n' +
            'Luffy will do anything to get the One Piece and become King of the Pirates!',
          poster_path: '/uiIB9ctqZFbfRXXimtpmZb5dusi.jpg',
          media_type: 'tv',
          original_language: 'ja',
          genre_ids: [10759, 35, 16],
          popularity: 47.468,
          first_air_date: '1999-10-20',
          vote_average: 8.725,
          vote_count: 5218,
          origin_country: ['JP'],
        },
        {
          adult: false,
          backdrop_path: '/z3BkMbCy5ajZPMyKEUwsPHuz2cV.jpg',
          id: 250307,
          name: 'The Pitt',
          original_name: 'The Pitt',
          overview:
            "The staff of Pittsburgh's Trauma Medical Center work around the clock to save lives in an overcrowded and underfunded emergency department.",
          poster_path: '/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [18],
          popularity: 142.1153,
          first_air_date: '2025-01-09',
          vote_average: 8.7,
          vote_count: 649,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg',
          id: 209867,
          name: "Frieren: Beyond Journey's End",
          original_name: '葬送のフリーレン',
          overview:
            "Decades after her party defeated the Demon King, an old friend's funeral launches the elf wizard Frieren on a journey of self-discovery.",
          poster_path: '/dqZENchTd7lp5zht7BdlqM7RBhD.jpg',
          media_type: 'tv',
          original_language: 'ja',
          genre_ids: [16, 10759, 18, 10765],
          popularity: 85.9914,
          first_air_date: '2023-09-29',
          vote_average: 8.806,
          vote_count: 780,
          origin_country: ['JP'],
        },
        {
          adult: false,
          backdrop_path: '/2VHbof9yaNhovEnaancBkXEULCT.jpg',
          id: 154385,
          name: 'BEEF',
          original_name: 'BEEF',
          overview:
            'A road rage incident between two strangers — a failing contractor and an unfulfilled entrepreneur — sparks a feud that brings out their darkest impulses.',
          poster_path: '/25ih0Xq2zWbxhhKxwhvswKYQyEr.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [35, 18],
          popularity: 70.9801,
          first_air_date: '2023-04-06',
          vote_average: 7.8,
          vote_count: 893,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/qpin8cASXEVtwhzNsprHYFiOAGk.jpg',
          id: 95479,
          name: 'JUJUTSU KAISEN',
          original_name: '呪術廻戦',
          overview:
            'Yuji Itadori is a boy with tremendous physical strength, though he lives a completely ordinary high school life. One day, to save a classmate who has been attacked by curses, he eats the finger of Ryomen Sukuna, taking the curse into his own soul. From then on, he shares one body with Ryomen Sukuna. Guided by the most powerful of sorcerers, Satoru Gojo, Itadori is admitted to Tokyo Jujutsu High School, an organization that fights the curses... and thus begins the heroic tale of a boy who became a curse to exorcise a curse, a life from which he could never turn back.',
          poster_path: '/6qQzMJG27XOJsyAEEIisoJB45j2.jpg',
          media_type: 'tv',
          original_language: 'ja',
          genre_ids: [16, 10759, 10765],
          popularity: 155.3905,
          first_air_date: '2020-10-03',
          vote_average: 8.558,
          vote_count: 4325,
          origin_country: ['JP'],
        },
        {
          adult: false,
          backdrop_path: '/qrTAc0ZtQ859Qu5O8cixJzNJpQs.jpg',
          id: 202555,
          name: 'Daredevil: Born Again',
          original_name: 'Daredevil: Born Again',
          overview:
            'Matt Murdock, a blind lawyer with heightened abilities, is fighting for justice through his bustling law firm, while former mob boss Wilson Fisk pursues his own political endeavors in New York. When their past identities begin to emerge, both men find themselves on an inevitable collision course.',
          poster_path: '/xDUoAsU8lQHOOoRkFiBuarmACDN.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [18, 10759, 80],
          popularity: 95.1212,
          first_air_date: '2025-03-04',
          vote_average: 8,
          vote_count: 751,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/9qrroces8C6R9aKr08hACNPVXdZ.jpg',
          id: 95557,
          name: 'INVINCIBLE',
          original_name: 'INVINCIBLE',
          overview:
            "Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own and enters into his father's tutelage.",
          poster_path: '/4tblBrslcKSifMVZ3TmtT2ukMor.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [16, 18, 10765, 10759],
          popularity: 238.8614,
          first_air_date: '2021-03-25',
          vote_average: 8.6,
          vote_count: 5567,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/7IY4wELVMvtUc78vPiuL8kQV2iA.jpg',
          id: 202411,
          name: 'Monarch: Legacy of Monsters',
          original_name: 'Monarch: Legacy of Monsters',
          overview:
            "After surviving Godzilla's attack on San Francisco, Cate is shaken yet again by a shocking secret. Amid monstrous threats, she embarks on a globetrotting adventure to learn the truth about her family—and the mysterious organization known as Monarch.",
          poster_path: '/7LBbaEaLSbqdviBYaSS1rRPMnrs.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [10765, 18, 10759],
          popularity: 125.8214,
          first_air_date: '2023-11-16',
          vote_average: 7.704,
          vote_count: 1159,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/x6y59dJBE1o0r4YRsWVQXE2nnlB.jpg',
          id: 65942,
          name: 'Re:ZERO -Starting Life in Another World-',
          original_name: 'Re:ゼロから始める異世界生活',
          overview:
            "Natsuki Subaru, an ordinary high school  student, is on his way home from the convenience store when he finds  himself transported to another world. As he's lost and confused in a new  world where he doesn't even know left from right, the only person to  reach out to him was a beautiful girl with silver hair. Determined to  repay her somehow for saving him from his own despair, Subaru agrees to  help the girl find something she's looking for.",
          poster_path: '/aRwmcX36r1ZpR5Xq5mmFcpUDQ8J.jpg',
          media_type: 'tv',
          original_language: 'ja',
          genre_ids: [16, 10759, 10765, 9648],
          popularity: 53.711,
          first_air_date: '2016-04-04',
          vote_average: 7.846,
          vote_count: 599,
          origin_country: ['JP'],
        },
        {
          adult: false,
          backdrop_path: '/nf3Vlxm3C9U1aKUUQHmKFZmxPSc.jpg',
          id: 56570,
          name: 'Outlander',
          original_name: 'Outlander',
          overview:
            "The story of Claire Randall, a married combat nurse from 1945 who is mysteriously swept back in time to 1743, where she is immediately thrown into an unknown world where her life is threatened. When she is forced to marry Jamie, a chivalrous and romantic young Scottish warrior, a passionate affair is ignited that tears Claire's heart between two vastly different men in two irreconcilable lives.",
          poster_path: '/bxBmfyzK0ARF9hqf2pbFWsddH14.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [18, 10765],
          popularity: 100.117,
          first_air_date: '2014-08-09',
          vote_average: 8.176,
          vote_count: 2808,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/6ekykPwvAywJRjFEnUoCFWTO9O3.jpg',
          id: 278573,
          name: 'Perfect Crown',
          original_name: '21세기 대군부인',
          overview:
            'In a 21st-century constitutional monarchy, a woman who has everything but remains a commoner crosses paths with a prince who, despite his royal lineage, feels powerless—leading to a love that defies social status.',
          poster_path: '/6CDHhHZ8lYkpSE3UkFKrqYeeSzz.jpg',
          media_type: 'tv',
          original_language: 'ko',
          genre_ids: [35, 18],
          popularity: 149.9629,
          first_air_date: '2026-04-10',
          vote_average: 9.111,
          vote_count: 10,
          origin_country: ['KR'],
        },
        {
          adult: false,
          backdrop_path: '/uekZzyLReK777QKO9xKwiPOelCQ.jpg',
          id: 279471,
          name: "Malcolm in the Middle: Life's Still Unfair",
          original_name: "Malcolm in the Middle: Life's Still Unfair",
          overview:
            'After shielding himself and his daughter from his family for over a decade, Malcolm is dragged back into their orbit when Hal and Lois demand his presence at their 40th anniversary party.',
          poster_path: '/4uXAZRYtcMfoX2XtY1gcUxLHhjj.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [35, 18],
          popularity: 139.7337,
          first_air_date: '2026-04-10',
          vote_average: 8.1,
          vote_count: 230,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/qD211Hb5XwFxrszzBBe5EUYJerh.jpg',
          id: 111110,
          name: 'ONE PIECE',
          original_name: 'ONE PIECE',
          overview:
            'With his straw hat and ragtag crew, young pirate Monkey D. Luffy goes on an epic voyage for treasure.',
          poster_path: '/blWCPEqDGLBuLB9u89CxP9ORQP4.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [10759, 10765],
          popularity: 59.5421,
          first_air_date: '2023-08-31',
          vote_average: 8.117,
          vote_count: 1711,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/kz1ceDJ7e8z8zIQNURJcGOoQ8WY.jpg',
          id: 295778,
          name: 'Scrubs',
          original_name: 'Scrubs',
          overview:
            'J.D. & Turk scrub in together for the first time in a long time–medicine has changed, interns have changed, but their bromance has stood the test of time. Characters new and old navigate the waters of Sacred Heart with laughter, heart and some surprises along the way.',
          poster_path: '/nNNM50G7p9C3n4vgidCiybsIdHA.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [35],
          popularity: 31.5206,
          first_air_date: '2026-02-25',
          vote_average: 8.155,
          vote_count: 42,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/5QsLvWh8J1mXl1W05wNJknMmhzR.jpg',
          id: 245927,
          name: 'Paradise',
          original_name: 'Paradise',
          overview:
            "The tranquility in a serene, wealthy community inhabited by some of the world's most prominent individuals explodes when a shocking murder occurs and a high stakes investigation unfolds.",
          poster_path: '/l8RqfhqEk04W5sSOjQ9zeWU1DyM.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [80, 18],
          popularity: 52.0111,
          first_air_date: '2025-01-26',
          vote_average: 7.448,
          vote_count: 420,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/n4VljCX22hbw3RwfxaY8FX8eLzN.jpg',
          id: 245842,
          name: 'Wistoria: Wand and Sword',
          original_name: '杖と剣のウィストリア',
          overview:
            'In a world where magic reigns, Will Serfort can’t cast a spell. Though hardworking, Will’s classmates think less of him for it. However, he has a secret strength: his sword. Can Will defy expectations with muscle over magic and blade over wand? Find out in this epic sword-and-sorcery adventure!',
          poster_path: '/5n0IZQA9MiXn5JBKZibtNhhFSAZ.jpg',
          media_type: 'tv',
          original_language: 'ja',
          genre_ids: [16, 10759, 10765],
          popularity: 31.583,
          first_air_date: '2024-07-07',
          vote_average: 7.557,
          vote_count: 98,
          origin_country: ['JP'],
        },
      ],
      total_pages: 500,
      total_results: 10000,
    };
    (global.fetch as jest.Mock).mockResolvedValue({
      ok: true,
      status: 200,
      json: async () => mockRes,
    });
    const res = await request(app).get('/api/tv/featured?timeframe=day');

    expect(res.status).toBe(200);
    expect(res.body).toEqual([
      {
        id: 124364,
        name: 'FROM',
        overview:
          'Unravel the mystery of a nightmarish town in middle America that traps all those who enter. As the unwilling residents fight to keep a sense of normalcy and search for a way out, they must also survive the threats of the surrounding forest – including the terrifying creatures that come out when the sun goes down.',
        first_air_date: '2022-02-20',
        genre_ids: [9648, 18, 10765],
        original_language: 'en',
        backdrop_path: '/6gN8DYnIEln8v7OhRy61c57w0Xy.jpg',
        poster_path: '/cjXLrg4R7FRPFafvuQ3SSznQOd9.jpg',
      },
      {
        id: 85552,
        name: 'Euphoria',
        overview:
          'A group of high school students navigate love and friendships in a world of drugs, sex, trauma, and social media.',
        first_air_date: '2019-06-16',
        genre_ids: [18],
        original_language: 'en',
        backdrop_path: '/GN2KFXiHPVV6sIw4v2P2pqCJty.jpg',
        poster_path: '/aJrG7OkoTMPWG5c8opz8a93AZPY.jpg',
      },
      {
        id: 76479,
        name: 'The Boys',
        overview:
          'A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.',
        first_air_date: '2019-07-25',
        genre_ids: [10765, 10759],
        original_language: 'en',
        backdrop_path: '/bq28ajZaoMyzEIm6REelqyqtEDZ.jpg',
        poster_path: '/in1R2dDc421JxsoRWaIIAqVI2KE.jpg',
      },
      {
        id: 289424,
        name: 'We Are All Trying Here',
        overview:
          'An aspiring director hits rock bottom after 20 years chasing his debut — until he meets an overwhelmed producer who helps him rediscover his self-worth.',
        first_air_date: '2026-04-18',
        genre_ids: [18],
        original_language: 'ko',
        backdrop_path: '/4ZXZi107TbfBJFGT4cnqbavQIoc.jpg',
        poster_path: '/c2jswCrMoqDEBEXwSAlrCWtXdfZ.jpg',
      },
      {
        id: 37854,
        name: 'One Piece',
        overview:
          'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
        first_air_date: '1999-10-20',
        genre_ids: [10759, 35, 16],
        original_language: 'ja',
        backdrop_path: '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
        poster_path: '/uiIB9ctqZFbfRXXimtpmZb5dusi.jpg',
      },
      {
        id: 250307,
        name: 'The Pitt',
        overview:
          "The staff of Pittsburgh's Trauma Medical Center work around the clock to save lives in an overcrowded and underfunded emergency department.",
        first_air_date: '2025-01-09',
        genre_ids: [18],
        original_language: 'en',
        backdrop_path: '/z3BkMbCy5ajZPMyKEUwsPHuz2cV.jpg',
        poster_path: '/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg',
      },
      {
        id: 209867,
        name: "Frieren: Beyond Journey's End",
        overview:
          "Decades after her party defeated the Demon King, an old friend's funeral launches the elf wizard Frieren on a journey of self-discovery.",
        first_air_date: '2023-09-29',
        genre_ids: [16, 10759, 18, 10765],
        original_language: 'ja',
        backdrop_path: '/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg',
        poster_path: '/dqZENchTd7lp5zht7BdlqM7RBhD.jpg',
      },
      {
        id: 154385,
        name: 'BEEF',
        overview:
          'A road rage incident between two strangers — a failing contractor and an unfulfilled entrepreneur — sparks a feud that brings out their darkest impulses.',
        first_air_date: '2023-04-06',
        genre_ids: [35, 18],
        original_language: 'en',
        backdrop_path: '/2VHbof9yaNhovEnaancBkXEULCT.jpg',
        poster_path: '/25ih0Xq2zWbxhhKxwhvswKYQyEr.jpg',
      },
      {
        id: 95479,
        name: 'JUJUTSU KAISEN',
        overview:
          'Yuji Itadori is a boy with tremendous physical strength, though he lives a completely ordinary high school life. One day, to save a classmate who has been attacked by curses, he eats the finger of Ryomen Sukuna, taking the curse into his own soul. From then on, he shares one body with Ryomen Sukuna. Guided by the most powerful of sorcerers, Satoru Gojo, Itadori is admitted to Tokyo Jujutsu High School, an organization that fights the curses... and thus begins the heroic tale of a boy who became a curse to exorcise a curse, a life from which he could never turn back.',
        first_air_date: '2020-10-03',
        genre_ids: [16, 10759, 10765],
        original_language: 'ja',
        backdrop_path: '/qpin8cASXEVtwhzNsprHYFiOAGk.jpg',
        poster_path: '/6qQzMJG27XOJsyAEEIisoJB45j2.jpg',
      },
      {
        id: 202555,
        name: 'Daredevil: Born Again',
        overview:
          'Matt Murdock, a blind lawyer with heightened abilities, is fighting for justice through his bustling law firm, while former mob boss Wilson Fisk pursues his own political endeavors in New York. When their past identities begin to emerge, both men find themselves on an inevitable collision course.',
        first_air_date: '2025-03-04',
        genre_ids: [18, 10759, 80],
        original_language: 'en',
        backdrop_path: '/qrTAc0ZtQ859Qu5O8cixJzNJpQs.jpg',
        poster_path: '/xDUoAsU8lQHOOoRkFiBuarmACDN.jpg',
      },
      {
        id: 95557,
        name: 'INVINCIBLE',
        overview:
          "Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own and enters into his father's tutelage.",
        first_air_date: '2021-03-25',
        genre_ids: [16, 18, 10765, 10759],
        original_language: 'en',
        backdrop_path: '/9qrroces8C6R9aKr08hACNPVXdZ.jpg',
        poster_path: '/4tblBrslcKSifMVZ3TmtT2ukMor.jpg',
      },
      {
        id: 202411,
        name: 'Monarch: Legacy of Monsters',
        overview:
          "After surviving Godzilla's attack on San Francisco, Cate is shaken yet again by a shocking secret. Amid monstrous threats, she embarks on a globetrotting adventure to learn the truth about her family—and the mysterious organization known as Monarch.",
        first_air_date: '2023-11-16',
        genre_ids: [10765, 18, 10759],
        original_language: 'en',
        backdrop_path: '/7IY4wELVMvtUc78vPiuL8kQV2iA.jpg',
        poster_path: '/7LBbaEaLSbqdviBYaSS1rRPMnrs.jpg',
      },
      {
        id: 65942,
        name: 'Re:ZERO -Starting Life in Another World-',
        overview:
          "Natsuki Subaru, an ordinary high school  student, is on his way home from the convenience store when he finds  himself transported to another world. As he's lost and confused in a new  world where he doesn't even know left from right, the only person to  reach out to him was a beautiful girl with silver hair. Determined to  repay her somehow for saving him from his own despair, Subaru agrees to  help the girl find something she's looking for.",
        first_air_date: '2016-04-04',
        genre_ids: [16, 10759, 10765, 9648],
        original_language: 'ja',
        backdrop_path: '/x6y59dJBE1o0r4YRsWVQXE2nnlB.jpg',
        poster_path: '/aRwmcX36r1ZpR5Xq5mmFcpUDQ8J.jpg',
      },
      {
        id: 56570,
        name: 'Outlander',
        overview:
          "The story of Claire Randall, a married combat nurse from 1945 who is mysteriously swept back in time to 1743, where she is immediately thrown into an unknown world where her life is threatened. When she is forced to marry Jamie, a chivalrous and romantic young Scottish warrior, a passionate affair is ignited that tears Claire's heart between two vastly different men in two irreconcilable lives.",
        first_air_date: '2014-08-09',
        genre_ids: [18, 10765],
        original_language: 'en',
        backdrop_path: '/nf3Vlxm3C9U1aKUUQHmKFZmxPSc.jpg',
        poster_path: '/bxBmfyzK0ARF9hqf2pbFWsddH14.jpg',
      },
      {
        id: 278573,
        name: 'Perfect Crown',
        overview:
          'In a 21st-century constitutional monarchy, a woman who has everything but remains a commoner crosses paths with a prince who, despite his royal lineage, feels powerless—leading to a love that defies social status.',
        first_air_date: '2026-04-10',
        genre_ids: [35, 18],
        original_language: 'ko',
        backdrop_path: '/6ekykPwvAywJRjFEnUoCFWTO9O3.jpg',
        poster_path: '/6CDHhHZ8lYkpSE3UkFKrqYeeSzz.jpg',
      },
      {
        id: 279471,
        name: "Malcolm in the Middle: Life's Still Unfair",
        overview:
          'After shielding himself and his daughter from his family for over a decade, Malcolm is dragged back into their orbit when Hal and Lois demand his presence at their 40th anniversary party.',
        first_air_date: '2026-04-10',
        genre_ids: [35, 18],
        original_language: 'en',
        backdrop_path: '/uekZzyLReK777QKO9xKwiPOelCQ.jpg',
        poster_path: '/4uXAZRYtcMfoX2XtY1gcUxLHhjj.jpg',
      },
      {
        id: 111110,
        name: 'ONE PIECE',
        overview:
          'With his straw hat and ragtag crew, young pirate Monkey D. Luffy goes on an epic voyage for treasure.',
        first_air_date: '2023-08-31',
        genre_ids: [10759, 10765],
        original_language: 'en',
        backdrop_path: '/qD211Hb5XwFxrszzBBe5EUYJerh.jpg',
        poster_path: '/blWCPEqDGLBuLB9u89CxP9ORQP4.jpg',
      },
      {
        id: 295778,
        name: 'Scrubs',
        overview:
          'J.D. & Turk scrub in together for the first time in a long time–medicine has changed, interns have changed, but their bromance has stood the test of time. Characters new and old navigate the waters of Sacred Heart with laughter, heart and some surprises along the way.',
        first_air_date: '2026-02-25',
        genre_ids: [35],
        original_language: 'en',
        backdrop_path: '/kz1ceDJ7e8z8zIQNURJcGOoQ8WY.jpg',
        poster_path: '/nNNM50G7p9C3n4vgidCiybsIdHA.jpg',
      },
      {
        id: 245927,
        name: 'Paradise',
        overview:
          "The tranquility in a serene, wealthy community inhabited by some of the world's most prominent individuals explodes when a shocking murder occurs and a high stakes investigation unfolds.",
        first_air_date: '2025-01-26',
        genre_ids: [80, 18],
        original_language: 'en',
        backdrop_path: '/5QsLvWh8J1mXl1W05wNJknMmhzR.jpg',
        poster_path: '/l8RqfhqEk04W5sSOjQ9zeWU1DyM.jpg',
      },
      {
        id: 245842,
        name: 'Wistoria: Wand and Sword',
        overview:
          'In a world where magic reigns, Will Serfort can’t cast a spell. Though hardworking, Will’s classmates think less of him for it. However, he has a secret strength: his sword. Can Will defy expectations with muscle over magic and blade over wand? Find out in this epic sword-and-sorcery adventure!',
        first_air_date: '2024-07-07',
        genre_ids: [16, 10759, 10765],
        original_language: 'ja',
        backdrop_path: '/n4VljCX22hbw3RwfxaY8FX8eLzN.jpg',
        poster_path: '/5n0IZQA9MiXn5JBKZibtNhhFSAZ.jpg',
      },
    ]);
  });
});

describe('Get featured with different lang', () => {
  it('Returns the featured for 1 day in es-AR', async () => {
    const mockRes = {
      page: 1,
      results: [
        {
          adult: false,
          backdrop_path: '/6gN8DYnIEln8v7OhRy61c57w0Xy.jpg',
          id: 124364,
          name: 'FROM',
          original_name: 'FROM',
          overview:
            'Desvela el misterio de un pueblo de pesadilla en el centro de Norteamérica que atrapa a todos los que entran. Mientras los residentes involuntarios luchan por mantener una sensación de normalidad y buscan una salida, también deben sobrevivir a las amenazas del bosque circundante, incluidas las aterradoras criaturas que salen cuando se pone el sol.',
          poster_path: '/cjXLrg4R7FRPFafvuQ3SSznQOd9.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [9648, 18, 10765],
          popularity: 175.2807,
          first_air_date: '2022-02-20',
          vote_average: 8.163,
          vote_count: 2561,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/GN2KFXiHPVV6sIw4v2P2pqCJty.jpg',
          id: 85552,
          name: 'Euphoria',
          original_name: 'Euphoria',
          overview:
            'Una reflexión sobre la adolescencia a través de un grupo de estudiantes de instituto que tienen que hacer frente a temas recurrentes de su edad, como la droga, el sexo y la violencia.',
          poster_path: '/6Sdm5XwdCnspdEF8fTFx6UJrl7o.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [18],
          popularity: 394.5648,
          first_air_date: '2019-06-16',
          vote_average: 8.3,
          vote_count: 10407,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/bq28ajZaoMyzEIm6REelqyqtEDZ.jpg',
          id: 76479,
          name: 'The Boys',
          original_name: 'The Boys',
          overview:
            'La serie tiene lugar en un mundo en el que los superhéroes representan el lado oscuro de la celebridad y la fama. Un grupo de vigilantes que se hacen llamar "The Boys" decide hacer todo lo posible por frenar a los superhéroes que están perjudicando a la sociedad, independientemente de los riesgos que ello conlleva.',
          poster_path: '/5kgY14oisiHcJ4zq0Xgq1e97PHm.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [10765, 10759],
          popularity: 646.578,
          first_air_date: '2019-07-25',
          vote_average: 8.44,
          vote_count: 11904,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/4ZXZi107TbfBJFGT4cnqbavQIoc.jpg',
          id: 289424,
          name: 'Hacemos lo que podemos',
          original_name: '모두가 자신의 무가치함과 싸우고 있다',
          overview:
            'Tras 20 años tratando de hacer su primera película, un aspirante a director toca fondo. Pero entonces conoce a una productora saturada que le ayuda a volver a creer en sí mismo.',
          poster_path: '/EQMMCm2IMUxU8m9Opq0trg7vAN.jpg',
          media_type: 'tv',
          original_language: 'ko',
          genre_ids: [18],
          popularity: 16.094,
          first_air_date: '2026-04-18',
          vote_average: 0,
          vote_count: 0,
          origin_country: ['KR'],
        },
        {
          adult: false,
          backdrop_path: '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
          id: 37854,
          name: 'One Piece',
          original_name: 'ワンピース',
          overview:
            'Esta historia se sitúa en el momento más álgido de la Gran Era de los Piratas, cuando el joven Monkey D. Luffy quiere llegar a ser el Rey de los Piratas y hacerse al fin con un legendario tesoro, el One Piece.',
          poster_path: '/oag7edI9flSMawmNySEiSEJAbrf.jpg',
          media_type: 'tv',
          original_language: 'ja',
          genre_ids: [10759, 35, 16],
          popularity: 47.468,
          first_air_date: '1999-10-20',
          vote_average: 8.725,
          vote_count: 5218,
          origin_country: ['JP'],
        },
        {
          adult: false,
          backdrop_path: '/z3BkMbCy5ajZPMyKEUwsPHuz2cV.jpg',
          id: 250307,
          name: 'The Pitt',
          original_name: 'The Pitt',
          overview:
            'The Pitt ofrece una visión realista de los retos a los que se enfrenta el personal sanitario en los Estados Unidos de hoy, visto a través de la lente de los héroes de primera línea que trabajan en un hospital de la actualidad en Pittsburgh, Pensilvania.',
          poster_path: '/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [18],
          popularity: 142.1153,
          first_air_date: '2025-01-09',
          vote_average: 8.7,
          vote_count: 649,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg',
          id: 209867,
          name: 'Frieren: Tras finalizar el viaje',
          original_name: '葬送のフリーレン',
          overview:
            'Décadas después de que su grupo derrotara al Rey Demonio, el funeral de un viejo amigo lleva a la hechicera elfa Frieren a embarcarse en un viaje de autodescubrimiento.',
          poster_path: '/3NyQpXmkaBVWgYM8miDHEFqGMCB.jpg',
          media_type: 'tv',
          original_language: 'ja',
          genre_ids: [16, 10759, 18, 10765],
          popularity: 85.9914,
          first_air_date: '2023-09-29',
          vote_average: 8.806,
          vote_count: 780,
          origin_country: ['JP'],
        },
        {
          adult: false,
          backdrop_path: '/2VHbof9yaNhovEnaancBkXEULCT.jpg',
          id: 154385,
          name: 'Bronca',
          original_name: 'BEEF',
          overview:
            'Un incidente de tráfico entre dos desconocidos (un contratista fracasado y una empresaria descontenta) desata un conflicto que saca a relucir su lado más oscuro.',
          poster_path: '/mymu4UmxV1ht8avuQYXjJpE1hL5.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [35, 18],
          popularity: 70.9801,
          first_air_date: '2023-04-06',
          vote_average: 7.8,
          vote_count: 893,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/qpin8cASXEVtwhzNsprHYFiOAGk.jpg',
          id: 95479,
          name: 'Jujutsu Kaisen',
          original_name: '呪術廻戦',
          overview:
            'La vida de Itadori cambia para siempre cuando, para salvar a un compañero de clase, se come el dedo de Ryomen Sukuna y absorbe una poderosa maldición.',
          poster_path: '/80eHrBl03xWcQYecoTO1LlkXpN1.jpg',
          media_type: 'tv',
          original_language: 'ja',
          genre_ids: [16, 10759, 10765],
          popularity: 155.3905,
          first_air_date: '2020-10-03',
          vote_average: 8.558,
          vote_count: 4325,
          origin_country: ['JP'],
        },
        {
          adult: false,
          backdrop_path: '/qrTAc0ZtQ859Qu5O8cixJzNJpQs.jpg',
          id: 202555,
          name: 'Daredevil: Born Again',
          original_name: 'Daredevil: Born Again',
          overview:
            'Matt Murdock, un abogado ciego con habilidades super desarrolladas lucha por la justicia desde su ajetreado bufete mientras el antiguo jefe mafioso Wilson Fisk emprende una carrera política en Nueva York. Cuando sus identidades pasadas empiezan a salir a la luz, ambos se ven abocados a un enfrentamiento inevitable.',
          poster_path: '/zNH50kOA5Zm5QSFqeIu3hJGuNdO.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [18, 10759, 80],
          popularity: 95.1212,
          first_air_date: '2025-03-04',
          vote_average: 8,
          vote_count: 751,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/9qrroces8C6R9aKr08hACNPVXdZ.jpg',
          id: 95557,
          name: 'INVENCIBLE',
          original_name: 'INVINCIBLE',
          overview:
            'Mark Grayson es un adolescente normal, excepto por el hecho de que su padre es el superhéroe más poderoso del planeta. Poco después de su decimoséptimo cumpleaños, Mark comienza a desarrollar sus propios poderes y entra en la tutela de su padre.',
          poster_path: '/AdcfiT5FsjUooyP7CrKzEGmP9K1.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [16, 18, 10765, 10759],
          popularity: 238.8614,
          first_air_date: '2021-03-25',
          vote_average: 8.6,
          vote_count: 5567,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/7IY4wELVMvtUc78vPiuL8kQV2iA.jpg',
          id: 202411,
          name: 'Monarch: El legado de los monstruos',
          original_name: 'Monarch: Legacy of Monsters',
          overview:
            'Tras sobrevivir al ataque de Godzilla en San Francisco, un espeluznante secreto vuelve a sobrecoger a Cate. En medio de amenazas monstruosas, se embarca en una aventura por todo el mundo para descubrir la verdad sobre su familia y la misteriosa organización conocida como Monarca.',
          poster_path: '/ufFSOyMYcuPhZpVs1obeYIzcnYY.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [10765, 18, 10759],
          popularity: 125.8214,
          first_air_date: '2023-11-16',
          vote_average: 7.704,
          vote_count: 1159,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/x6y59dJBE1o0r4YRsWVQXE2nnlB.jpg',
          id: 65942,
          name: 'Re:Zero - Empezar de cero en un mundo diferente',
          original_name: 'Re:ゼロから始める異世界生活',
          overview:
            'Subaru Natsuki es un estudiante corriente de preparatoria que conoce a una hermosa chica de pelo plateado de otro mundo que lo rescata. Para devolverle el favor decide quedarse con ella, pero el destino con el que carga la muchacha es mucho más pesado de lo que Subaru puede imaginar. Los enemigos atacan sin descanso, uno tras otro, hasta que finalmente mueren tanto él como la chica. Subaru no quiere que la chica resulte herida, con lo que jura acabar con cualquier enemigo, con cualquier destino que le aguarde, siempre por protegerla.',
          poster_path: '/ccG0ZfXOQ0834bIus4SwZrXtkyM.jpg',
          media_type: 'tv',
          original_language: 'ja',
          genre_ids: [16, 10759, 10765, 9648],
          popularity: 53.711,
          first_air_date: '2016-04-04',
          vote_average: 7.846,
          vote_count: 599,
          origin_country: ['JP'],
        },
        {
          adult: false,
          backdrop_path: '/nf3Vlxm3C9U1aKUUQHmKFZmxPSc.jpg',
          id: 56570,
          name: 'Outlander',
          original_name: 'Outlander',
          overview:
            'Sigue la historia de Claire Randall, una enfermera de combate casada en los años 40, que misteriosamente es arrastrada atrás en el tiempo hasta 1743, donde se lanza de inmediato a un mundo desconocido, viéndose amenazada su propia vida. Cuando se ve obligada a casarse con Jamie Fraser, un joven guerrero escocés caballeroso y romántico, Claire comienza un pasional triángulo entre dos hombres muy diferentes con dos vidas irreconciliables.',
          poster_path: '/wwxKbrMlwMrC06B7aCIkDy3SAo6.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [18, 10765],
          popularity: 100.117,
          first_air_date: '2014-08-09',
          vote_average: 8.2,
          vote_count: 2807,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/6ekykPwvAywJRjFEnUoCFWTO9O3.jpg',
          id: 278573,
          name: 'La corona perfecta',
          original_name: '21세기 대군부인',
          overview:
            'En una Corea moderna con una monarquía constitucional, una heredera de Chaebol y un príncipe impotente contraen un matrimonio por contrato, descubriendo el amor y el coraje mientras enfrentan barreras sociales y cicatrices personales.',
          poster_path: '/51EIbzw2pvsi73UXGtuHaZGJfQa.jpg',
          media_type: 'tv',
          original_language: 'ko',
          genre_ids: [35, 18],
          popularity: 149.9629,
          first_air_date: '2026-04-10',
          vote_average: 9.111,
          vote_count: 10,
          origin_country: ['KR'],
        },
        {
          adult: false,
          backdrop_path: '/uekZzyLReK777QKO9xKwiPOelCQ.jpg',
          id: 279471,
          name: 'Malcolm: De mal en peor',
          original_name: "Malcolm in the Middle: Life's Still Unfair",
          overview:
            'Han pasado veinte años y Malcolm y su familia siguen sin aprender absolutamente nada.',
          poster_path: '/hsRxfDXuecLGIKxe9rz7aJSgRdD.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [35, 18],
          popularity: 139.7337,
          first_air_date: '2026-04-10',
          vote_average: 8.1,
          vote_count: 230,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/qD211Hb5XwFxrszzBBe5EUYJerh.jpg',
          id: 111110,
          name: 'ONE PIECE',
          original_name: 'ONE PIECE',
          overview:
            'El joven pirata Monkey D. Luffy y su variopinta tripulación emprenden un viaje épico en busca de un tesoro.',
          poster_path: '/gCZ18cl7Pc4tgiwMPWHTgjABrhy.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [10759, 10765],
          popularity: 59.5421,
          first_air_date: '2023-08-31',
          vote_average: 8.117,
          vote_count: 1711,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/kz1ceDJ7e8z8zIQNURJcGOoQ8WY.jpg',
          id: 295778,
          name: 'Scrubs',
          original_name: 'Scrubs',
          overview:
            'Los viejos amigos JD y Turk se reúnen por primera vez en mucho tiempo y descubren que la medicina ha cambiado, los internos han cambiado, pero su amistad ha resistido la prueba del tiempo.',
          poster_path: '/nNNM50G7p9C3n4vgidCiybsIdHA.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [35],
          popularity: 31.5206,
          first_air_date: '2026-02-25',
          vote_average: 8.155,
          vote_count: 42,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/5QsLvWh8J1mXl1W05wNJknMmhzR.jpg',
          id: 245927,
          name: 'Paradise',
          original_name: 'Paradise',
          overview:
            'En una serena comunidad habitada por algunas de las personas más prominentes del mundo, la tranquilidad estalla cuando se produce un espeluznante asesinato y se desencadena una investigación de alto riesgo. Xavier Collins, jefe del Servicio Secreto de la Casa Blanca, es rápidamente investigado por la muerte del presidente, al que descubre junto a su cama.',
          poster_path: '/s1rvfglVgSR8tnLuHRbPpEgGQcS.jpg',
          media_type: 'tv',
          original_language: 'en',
          genre_ids: [80, 18],
          popularity: 52.0111,
          first_air_date: '2025-01-26',
          vote_average: 7.448,
          vote_count: 420,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/n4VljCX22hbw3RwfxaY8FX8eLzN.jpg',
          id: 245842,
          name: 'Wistoria: varita y espada',
          original_name: '杖と剣のウィストリア',
          overview:
            'En un mundo donde reina la magia, Will Serfort no puede lanzar un hechizo. Aunque es muy trabajador, sus compañeros de clase piensan menos de él por ello. Sin embargo, tiene una fuerza secreta: su espada. ¿Podrá Will desafiar las expectativas con fuerza sobre magia y espada sobre varita? ¡Descúbrelo en esta épica aventura de espada y brujería!',
          poster_path: '/v8gkKx1BvD3AH0MjwgCPbHTwxPE.jpg',
          media_type: 'tv',
          original_language: 'ja',
          genre_ids: [16, 10759, 10765],
          popularity: 31.583,
          first_air_date: '2024-07-07',
          vote_average: 7.557,
          vote_count: 98,
          origin_country: ['JP'],
        },
      ],
      total_pages: 500,
      total_results: 10000,
    };
    (global.fetch as jest.Mock).mockResolvedValue({
      ok: true,
      status: 200,
      json: async () => mockRes,
    });
    const res = await request(app).get('/api/tv/featured?language=es-AR&timeframe=day');

    expect(res.status).toBe(200);
    expect(res.body).toEqual([
      {
        id: 124364,
        name: 'FROM',
        overview:
          'Desvela el misterio de un pueblo de pesadilla en el centro de Norteamérica que atrapa a todos los que entran. Mientras los residentes involuntarios luchan por mantener una sensación de normalidad y buscan una salida, también deben sobrevivir a las amenazas del bosque circundante, incluidas las aterradoras criaturas que salen cuando se pone el sol.',
        first_air_date: '2022-02-20',
        genre_ids: [9648, 18, 10765],
        original_language: 'en',
        backdrop_path: '/6gN8DYnIEln8v7OhRy61c57w0Xy.jpg',
        poster_path: '/cjXLrg4R7FRPFafvuQ3SSznQOd9.jpg',
      },
      {
        id: 85552,
        name: 'Euphoria',
        overview:
          'Una reflexión sobre la adolescencia a través de un grupo de estudiantes de instituto que tienen que hacer frente a temas recurrentes de su edad, como la droga, el sexo y la violencia.',
        first_air_date: '2019-06-16',
        genre_ids: [18],
        original_language: 'en',
        backdrop_path: '/GN2KFXiHPVV6sIw4v2P2pqCJty.jpg',
        poster_path: '/6Sdm5XwdCnspdEF8fTFx6UJrl7o.jpg',
      },
      {
        id: 76479,
        name: 'The Boys',
        overview:
          'La serie tiene lugar en un mundo en el que los superhéroes representan el lado oscuro de la celebridad y la fama. Un grupo de vigilantes que se hacen llamar "The Boys" decide hacer todo lo posible por frenar a los superhéroes que están perjudicando a la sociedad, independientemente de los riesgos que ello conlleva.',
        first_air_date: '2019-07-25',
        genre_ids: [10765, 10759],
        original_language: 'en',
        backdrop_path: '/bq28ajZaoMyzEIm6REelqyqtEDZ.jpg',
        poster_path: '/5kgY14oisiHcJ4zq0Xgq1e97PHm.jpg',
      },
      {
        id: 289424,
        name: 'Hacemos lo que podemos',
        overview:
          'Tras 20 años tratando de hacer su primera película, un aspirante a director toca fondo. Pero entonces conoce a una productora saturada que le ayuda a volver a creer en sí mismo.',
        first_air_date: '2026-04-18',
        genre_ids: [18],
        original_language: 'ko',
        backdrop_path: '/4ZXZi107TbfBJFGT4cnqbavQIoc.jpg',
        poster_path: '/EQMMCm2IMUxU8m9Opq0trg7vAN.jpg',
      },
      {
        id: 37854,
        name: 'One Piece',
        overview:
          'Esta historia se sitúa en el momento más álgido de la Gran Era de los Piratas, cuando el joven Monkey D. Luffy quiere llegar a ser el Rey de los Piratas y hacerse al fin con un legendario tesoro, el One Piece.',
        first_air_date: '1999-10-20',
        genre_ids: [10759, 35, 16],
        original_language: 'ja',
        backdrop_path: '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
        poster_path: '/oag7edI9flSMawmNySEiSEJAbrf.jpg',
      },
      {
        id: 250307,
        name: 'The Pitt',
        overview:
          'The Pitt ofrece una visión realista de los retos a los que se enfrenta el personal sanitario en los Estados Unidos de hoy, visto a través de la lente de los héroes de primera línea que trabajan en un hospital de la actualidad en Pittsburgh, Pensilvania.',
        first_air_date: '2025-01-09',
        genre_ids: [18],
        original_language: 'en',
        backdrop_path: '/z3BkMbCy5ajZPMyKEUwsPHuz2cV.jpg',
        poster_path: '/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg',
      },
      {
        id: 209867,
        name: 'Frieren: Tras finalizar el viaje',
        overview:
          'Décadas después de que su grupo derrotara al Rey Demonio, el funeral de un viejo amigo lleva a la hechicera elfa Frieren a embarcarse en un viaje de autodescubrimiento.',
        first_air_date: '2023-09-29',
        genre_ids: [16, 10759, 18, 10765],
        original_language: 'ja',
        backdrop_path: '/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg',
        poster_path: '/3NyQpXmkaBVWgYM8miDHEFqGMCB.jpg',
      },
      {
        id: 154385,
        name: 'Bronca',
        overview:
          'Un incidente de tráfico entre dos desconocidos (un contratista fracasado y una empresaria descontenta) desata un conflicto que saca a relucir su lado más oscuro.',
        first_air_date: '2023-04-06',
        genre_ids: [35, 18],
        original_language: 'en',
        backdrop_path: '/2VHbof9yaNhovEnaancBkXEULCT.jpg',
        poster_path: '/mymu4UmxV1ht8avuQYXjJpE1hL5.jpg',
      },
      {
        id: 95479,
        name: 'Jujutsu Kaisen',
        overview:
          'La vida de Itadori cambia para siempre cuando, para salvar a un compañero de clase, se come el dedo de Ryomen Sukuna y absorbe una poderosa maldición.',
        first_air_date: '2020-10-03',
        genre_ids: [16, 10759, 10765],
        original_language: 'ja',
        backdrop_path: '/qpin8cASXEVtwhzNsprHYFiOAGk.jpg',
        poster_path: '/80eHrBl03xWcQYecoTO1LlkXpN1.jpg',
      },
      {
        id: 202555,
        name: 'Daredevil: Born Again',
        overview:
          'Matt Murdock, un abogado ciego con habilidades super desarrolladas lucha por la justicia desde su ajetreado bufete mientras el antiguo jefe mafioso Wilson Fisk emprende una carrera política en Nueva York. Cuando sus identidades pasadas empiezan a salir a la luz, ambos se ven abocados a un enfrentamiento inevitable.',
        first_air_date: '2025-03-04',
        genre_ids: [18, 10759, 80],
        original_language: 'en',
        backdrop_path: '/qrTAc0ZtQ859Qu5O8cixJzNJpQs.jpg',
        poster_path: '/zNH50kOA5Zm5QSFqeIu3hJGuNdO.jpg',
      },
      {
        id: 95557,
        name: 'INVENCIBLE',
        overview:
          'Mark Grayson es un adolescente normal, excepto por el hecho de que su padre es el superhéroe más poderoso del planeta. Poco después de su decimoséptimo cumpleaños, Mark comienza a desarrollar sus propios poderes y entra en la tutela de su padre.',
        first_air_date: '2021-03-25',
        genre_ids: [16, 18, 10765, 10759],
        original_language: 'en',
        backdrop_path: '/9qrroces8C6R9aKr08hACNPVXdZ.jpg',
        poster_path: '/AdcfiT5FsjUooyP7CrKzEGmP9K1.jpg',
      },
      {
        id: 202411,
        name: 'Monarch: El legado de los monstruos',
        overview:
          'Tras sobrevivir al ataque de Godzilla en San Francisco, un espeluznante secreto vuelve a sobrecoger a Cate. En medio de amenazas monstruosas, se embarca en una aventura por todo el mundo para descubrir la verdad sobre su familia y la misteriosa organización conocida como Monarca.',
        first_air_date: '2023-11-16',
        genre_ids: [10765, 18, 10759],
        original_language: 'en',
        backdrop_path: '/7IY4wELVMvtUc78vPiuL8kQV2iA.jpg',
        poster_path: '/ufFSOyMYcuPhZpVs1obeYIzcnYY.jpg',
      },
      {
        id: 65942,
        name: 'Re:Zero - Empezar de cero en un mundo diferente',
        overview:
          'Subaru Natsuki es un estudiante corriente de preparatoria que conoce a una hermosa chica de pelo plateado de otro mundo que lo rescata. Para devolverle el favor decide quedarse con ella, pero el destino con el que carga la muchacha es mucho más pesado de lo que Subaru puede imaginar. Los enemigos atacan sin descanso, uno tras otro, hasta que finalmente mueren tanto él como la chica. Subaru no quiere que la chica resulte herida, con lo que jura acabar con cualquier enemigo, con cualquier destino que le aguarde, siempre por protegerla.',
        first_air_date: '2016-04-04',
        genre_ids: [16, 10759, 10765, 9648],
        original_language: 'ja',
        backdrop_path: '/x6y59dJBE1o0r4YRsWVQXE2nnlB.jpg',
        poster_path: '/ccG0ZfXOQ0834bIus4SwZrXtkyM.jpg',
      },
      {
        id: 56570,
        name: 'Outlander',
        overview:
          'Sigue la historia de Claire Randall, una enfermera de combate casada en los años 40, que misteriosamente es arrastrada atrás en el tiempo hasta 1743, donde se lanza de inmediato a un mundo desconocido, viéndose amenazada su propia vida. Cuando se ve obligada a casarse con Jamie Fraser, un joven guerrero escocés caballeroso y romántico, Claire comienza un pasional triángulo entre dos hombres muy diferentes con dos vidas irreconciliables.',
        first_air_date: '2014-08-09',
        genre_ids: [18, 10765],
        original_language: 'en',
        backdrop_path: '/nf3Vlxm3C9U1aKUUQHmKFZmxPSc.jpg',
        poster_path: '/wwxKbrMlwMrC06B7aCIkDy3SAo6.jpg',
      },
      {
        id: 278573,
        name: 'La corona perfecta',
        overview:
          'En una Corea moderna con una monarquía constitucional, una heredera de Chaebol y un príncipe impotente contraen un matrimonio por contrato, descubriendo el amor y el coraje mientras enfrentan barreras sociales y cicatrices personales.',
        first_air_date: '2026-04-10',
        genre_ids: [35, 18],
        original_language: 'ko',
        backdrop_path: '/6ekykPwvAywJRjFEnUoCFWTO9O3.jpg',
        poster_path: '/51EIbzw2pvsi73UXGtuHaZGJfQa.jpg',
      },
      {
        id: 279471,
        name: 'Malcolm: De mal en peor',
        overview:
          'Han pasado veinte años y Malcolm y su familia siguen sin aprender absolutamente nada.',
        first_air_date: '2026-04-10',
        genre_ids: [35, 18],
        original_language: 'en',
        backdrop_path: '/uekZzyLReK777QKO9xKwiPOelCQ.jpg',
        poster_path: '/hsRxfDXuecLGIKxe9rz7aJSgRdD.jpg',
      },
      {
        id: 111110,
        name: 'ONE PIECE',
        overview:
          'El joven pirata Monkey D. Luffy y su variopinta tripulación emprenden un viaje épico en busca de un tesoro.',
        first_air_date: '2023-08-31',
        genre_ids: [10759, 10765],
        original_language: 'en',
        backdrop_path: '/qD211Hb5XwFxrszzBBe5EUYJerh.jpg',
        poster_path: '/gCZ18cl7Pc4tgiwMPWHTgjABrhy.jpg',
      },
      {
        id: 295778,
        name: 'Scrubs',
        overview:
          'Los viejos amigos JD y Turk se reúnen por primera vez en mucho tiempo y descubren que la medicina ha cambiado, los internos han cambiado, pero su amistad ha resistido la prueba del tiempo.',
        first_air_date: '2026-02-25',
        genre_ids: [35],
        original_language: 'en',
        backdrop_path: '/kz1ceDJ7e8z8zIQNURJcGOoQ8WY.jpg',
        poster_path: '/nNNM50G7p9C3n4vgidCiybsIdHA.jpg',
      },
      {
        id: 245927,
        name: 'Paradise',
        overview:
          'En una serena comunidad habitada por algunas de las personas más prominentes del mundo, la tranquilidad estalla cuando se produce un espeluznante asesinato y se desencadena una investigación de alto riesgo. Xavier Collins, jefe del Servicio Secreto de la Casa Blanca, es rápidamente investigado por la muerte del presidente, al que descubre junto a su cama.',
        first_air_date: '2025-01-26',
        genre_ids: [80, 18],
        original_language: 'en',
        backdrop_path: '/5QsLvWh8J1mXl1W05wNJknMmhzR.jpg',
        poster_path: '/s1rvfglVgSR8tnLuHRbPpEgGQcS.jpg',
      },
      {
        id: 245842,
        name: 'Wistoria: varita y espada',
        overview:
          'En un mundo donde reina la magia, Will Serfort no puede lanzar un hechizo. Aunque es muy trabajador, sus compañeros de clase piensan menos de él por ello. Sin embargo, tiene una fuerza secreta: su espada. ¿Podrá Will desafiar las expectativas con fuerza sobre magia y espada sobre varita? ¡Descúbrelo en esta épica aventura de espada y brujería!',
        first_air_date: '2024-07-07',
        genre_ids: [16, 10759, 10765],
        original_language: 'ja',
        backdrop_path: '/n4VljCX22hbw3RwfxaY8FX8eLzN.jpg',
        poster_path: '/v8gkKx1BvD3AH0MjwgCPbHTwxPE.jpg',
      },
    ]);
  });
});

describe('Get featured with missing api key', () => {
  it('Handles a missing API key', async () => {
    delete process.env.TMDB_API_KEY;
    const res = await request(app).get('/api/tv/featured');

    expect(res.status).toBe(500);
  });
});

describe('Get featured when no tmdb response', () => {
  it('Handles TMDB not responding', async () => {
    const res = await request(app).get('/api/tv/featured');

    expect(res.status).toBe(502);
  });
});
